/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesMessagesCreate } from "../funcs/messagesMessagesCreate.js";
import { messagesMessagesGet } from "../funcs/messagesMessagesGet.js";
import { messagesMessagesList } from "../funcs/messagesMessagesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Messages extends ClientSDK {
  async messagesList(
    options?: RequestOptions,
  ): Promise<Array<components.Message>> {
    return unwrapAsync(messagesMessagesList(
      this,
      options,
    ));
  }

  async messagesCreate(
    request: components.MessageCreate,
    options?: RequestOptions,
  ): Promise<components.Message> {
    return unwrapAsync(messagesMessagesCreate(
      this,
      request,
      options,
    ));
  }

  async messagesGet(
    request: operations.MessagesGetRequest,
    options?: RequestOptions,
  ): Promise<components.Message> {
    return unwrapAsync(messagesMessagesGet(
      this,
      request,
      options,
    ));
  }
}
