/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Files } from "./files.js";
import { Messages } from "./messages.js";
import { Runs } from "./runs.js";
import { Threads } from "./threads.js";

export class Edgen extends ClientSDK {
  private _files?: Files;
  get files(): Files {
    return (this._files ??= new Files(this._options));
  }

  private _messages?: Messages;
  get messages(): Messages {
    return (this._messages ??= new Messages(this._options));
  }

  private _runs?: Runs;
  get runs(): Runs {
    return (this._runs ??= new Runs(this._options));
  }

  private _threads?: Threads;
  get threads(): Threads {
    return (this._threads ??= new Threads(this._options));
  }
}
