/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type ConvertCreate = {
  inputFileId: string;
};

/** @internal */
export const ConvertCreate$inboundSchema: z.ZodType<
  ConvertCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  input_file_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "input_file_id": "inputFileId",
  });
});

/** @internal */
export type ConvertCreate$Outbound = {
  input_file_id: string;
};

/** @internal */
export const ConvertCreate$outboundSchema: z.ZodType<
  ConvertCreate$Outbound,
  z.ZodTypeDef,
  ConvertCreate
> = z.object({
  inputFileId: z.string(),
}).transform((v) => {
  return remap$(v, {
    inputFileId: "input_file_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConvertCreate$ {
  /** @deprecated use `ConvertCreate$inboundSchema` instead. */
  export const inboundSchema = ConvertCreate$inboundSchema;
  /** @deprecated use `ConvertCreate$outboundSchema` instead. */
  export const outboundSchema = ConvertCreate$outboundSchema;
  /** @deprecated use `ConvertCreate$Outbound` instead. */
  export type Outbound = ConvertCreate$Outbound;
}
