/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type FileT = {
  accountId: string;
  createdAt: Date;
  expiresAt: Date;
  filename: string;
  id: string;
  numPages: number;
  size: number;
  url: string;
};

/** @internal */
export const FileT$inboundSchema: z.ZodType<FileT, z.ZodTypeDef, unknown> = z
  .object({
    account_id: z.string(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    expires_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    filename: z.string(),
    id: z.string(),
    num_pages: z.number().int(),
    size: z.number().int(),
    url: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "account_id": "accountId",
      "created_at": "createdAt",
      "expires_at": "expiresAt",
      "num_pages": "numPages",
    });
  });

/** @internal */
export type FileT$Outbound = {
  account_id: string;
  created_at: string;
  expires_at: string;
  filename: string;
  id: string;
  num_pages: number;
  size: number;
  url: string;
};

/** @internal */
export const FileT$outboundSchema: z.ZodType<
  FileT$Outbound,
  z.ZodTypeDef,
  FileT
> = z.object({
  accountId: z.string(),
  createdAt: z.date().transform(v => v.toISOString()),
  expiresAt: z.date().transform(v => v.toISOString()),
  filename: z.string(),
  id: z.string(),
  numPages: z.number().int(),
  size: z.number().int(),
  url: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountId: "account_id",
    createdAt: "created_at",
    expiresAt: "expires_at",
    numPages: "num_pages",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileT$ {
  /** @deprecated use `FileT$inboundSchema` instead. */
  export const inboundSchema = FileT$inboundSchema;
  /** @deprecated use `FileT$outboundSchema` instead. */
  export const outboundSchema = FileT$outboundSchema;
  /** @deprecated use `FileT$Outbound` instead. */
  export type Outbound = FileT$Outbound;
}

export function fileTToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

export function fileTFromJSON(
  jsonString: string,
): SafeParseResult<FileT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileT' from JSON`,
  );
}
