/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { blobLikeSchema } from "../../types/blobs.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Data = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type FileUpload = {
  data: Data | Blob;
};

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.instanceof(ReadableStream<Uint8Array>),
      z.instanceof(Blob),
      z.instanceof(ArrayBuffer),
      z.instanceof(Uint8Array),
    ]),
  });

/** @internal */
export type Data$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> =
  z.object({
    fileName: z.string(),
    content: z.union([
      z.instanceof(ReadableStream<Uint8Array>),
      z.instanceof(Blob),
      z.instanceof(ArrayBuffer),
      z.instanceof(Uint8Array),
    ]),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Data$ {
  /** @deprecated use `Data$inboundSchema` instead. */
  export const inboundSchema = Data$inboundSchema;
  /** @deprecated use `Data$outboundSchema` instead. */
  export const outboundSchema = Data$outboundSchema;
  /** @deprecated use `Data$Outbound` instead. */
  export type Outbound = Data$Outbound;
}

export function dataToJSON(data: Data): string {
  return JSON.stringify(Data$outboundSchema.parse(data));
}

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const FileUpload$inboundSchema: z.ZodType<
  FileUpload,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => Data$inboundSchema),
});

/** @internal */
export type FileUpload$Outbound = {
  data: Data$Outbound | Blob;
};

/** @internal */
export const FileUpload$outboundSchema: z.ZodType<
  FileUpload$Outbound,
  z.ZodTypeDef,
  FileUpload
> = z.object({
  data: z.lazy(() => Data$outboundSchema).or(blobLikeSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileUpload$ {
  /** @deprecated use `FileUpload$inboundSchema` instead. */
  export const inboundSchema = FileUpload$inboundSchema;
  /** @deprecated use `FileUpload$outboundSchema` instead. */
  export const outboundSchema = FileUpload$outboundSchema;
  /** @deprecated use `FileUpload$Outbound` instead. */
  export type Outbound = FileUpload$Outbound;
}

export function fileUploadToJSON(fileUpload: FileUpload): string {
  return JSON.stringify(FileUpload$outboundSchema.parse(fileUpload));
}

export function fileUploadFromJSON(
  jsonString: string,
): SafeParseResult<FileUpload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileUpload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileUpload' from JSON`,
  );
}
