/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  MessageRole,
  MessageRole$inboundSchema,
  MessageRole$outboundSchema,
} from "./messagerole.js";

export type MessageCreate = {
  content: string;
  role: MessageRole;
  threadId: string;
};

/** @internal */
export const MessageCreate$inboundSchema: z.ZodType<
  MessageCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.string(),
  role: MessageRole$inboundSchema,
  thread_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "thread_id": "threadId",
  });
});

/** @internal */
export type MessageCreate$Outbound = {
  content: string;
  role: string;
  thread_id: string;
};

/** @internal */
export const MessageCreate$outboundSchema: z.ZodType<
  MessageCreate$Outbound,
  z.ZodTypeDef,
  MessageCreate
> = z.object({
  content: z.string(),
  role: MessageRole$outboundSchema,
  threadId: z.string(),
}).transform((v) => {
  return remap$(v, {
    threadId: "thread_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessageCreate$ {
  /** @deprecated use `MessageCreate$inboundSchema` instead. */
  export const inboundSchema = MessageCreate$inboundSchema;
  /** @deprecated use `MessageCreate$outboundSchema` instead. */
  export const outboundSchema = MessageCreate$outboundSchema;
  /** @deprecated use `MessageCreate$Outbound` instead. */
  export type Outbound = MessageCreate$Outbound;
}

export function messageCreateToJSON(messageCreate: MessageCreate): string {
  return JSON.stringify(MessageCreate$outboundSchema.parse(messageCreate));
}

export function messageCreateFromJSON(
  jsonString: string,
): SafeParseResult<MessageCreate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageCreate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageCreate' from JSON`,
  );
}
