/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  RunStatus,
  RunStatus$inboundSchema,
  RunStatus$outboundSchema,
} from "./runstatus.js";

export type Run = {
  accountId: string;
  createdAt: Date;
  credits?: number | null | undefined;
  finishedAt?: Date | null | undefined;
  id: string;
  inputFileId: string;
  inputTokens?: number | null | undefined;
  outputFileId?: string | null | undefined;
  outputTokens?: number | null | undefined;
  status: RunStatus;
  targetLanguage: string;
};

/** @internal */
export const Run$inboundSchema: z.ZodType<Run, z.ZodTypeDef, unknown> = z
  .object({
    account_id: z.string(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    credits: z.nullable(z.number().int()).optional(),
    finished_at: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ).optional(),
    id: z.string(),
    input_file_id: z.string(),
    input_tokens: z.nullable(z.number().int()).optional(),
    output_file_id: z.nullable(z.string()).optional(),
    output_tokens: z.nullable(z.number().int()).optional(),
    status: RunStatus$inboundSchema,
    target_language: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "account_id": "accountId",
      "created_at": "createdAt",
      "finished_at": "finishedAt",
      "input_file_id": "inputFileId",
      "input_tokens": "inputTokens",
      "output_file_id": "outputFileId",
      "output_tokens": "outputTokens",
      "target_language": "targetLanguage",
    });
  });

/** @internal */
export type Run$Outbound = {
  account_id: string;
  created_at: string;
  credits?: number | null | undefined;
  finished_at?: string | null | undefined;
  id: string;
  input_file_id: string;
  input_tokens?: number | null | undefined;
  output_file_id?: string | null | undefined;
  output_tokens?: number | null | undefined;
  status: string;
  target_language: string;
};

/** @internal */
export const Run$outboundSchema: z.ZodType<Run$Outbound, z.ZodTypeDef, Run> = z
  .object({
    accountId: z.string(),
    createdAt: z.date().transform(v => v.toISOString()),
    credits: z.nullable(z.number().int()).optional(),
    finishedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
    id: z.string(),
    inputFileId: z.string(),
    inputTokens: z.nullable(z.number().int()).optional(),
    outputFileId: z.nullable(z.string()).optional(),
    outputTokens: z.nullable(z.number().int()).optional(),
    status: RunStatus$outboundSchema,
    targetLanguage: z.string(),
  }).transform((v) => {
    return remap$(v, {
      accountId: "account_id",
      createdAt: "created_at",
      finishedAt: "finished_at",
      inputFileId: "input_file_id",
      inputTokens: "input_tokens",
      outputFileId: "output_file_id",
      outputTokens: "output_tokens",
      targetLanguage: "target_language",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Run$ {
  /** @deprecated use `Run$inboundSchema` instead. */
  export const inboundSchema = Run$inboundSchema;
  /** @deprecated use `Run$outboundSchema` instead. */
  export const outboundSchema = Run$outboundSchema;
  /** @deprecated use `Run$Outbound` instead. */
  export type Outbound = Run$Outbound;
}

export function runToJSON(run: Run): string {
  return JSON.stringify(Run$outboundSchema.parse(run));
}

export function runFromJSON(
  jsonString: string,
): SafeParseResult<Run, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Run$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Run' from JSON`,
  );
}
