/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RunCreate = {
  inputFileId: string;
  targetLanguage: string;
};

/** @internal */
export const RunCreate$inboundSchema: z.ZodType<
  RunCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  input_file_id: z.string(),
  target_language: z.string(),
}).transform((v) => {
  return remap$(v, {
    "input_file_id": "inputFileId",
    "target_language": "targetLanguage",
  });
});

/** @internal */
export type RunCreate$Outbound = {
  input_file_id: string;
  target_language: string;
};

/** @internal */
export const RunCreate$outboundSchema: z.ZodType<
  RunCreate$Outbound,
  z.ZodTypeDef,
  RunCreate
> = z.object({
  inputFileId: z.string(),
  targetLanguage: z.string(),
}).transform((v) => {
  return remap$(v, {
    inputFileId: "input_file_id",
    targetLanguage: "target_language",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunCreate$ {
  /** @deprecated use `RunCreate$inboundSchema` instead. */
  export const inboundSchema = RunCreate$inboundSchema;
  /** @deprecated use `RunCreate$outboundSchema` instead. */
  export const outboundSchema = RunCreate$outboundSchema;
  /** @deprecated use `RunCreate$Outbound` instead. */
  export type Outbound = RunCreate$Outbound;
}

export function runCreateToJSON(runCreate: RunCreate): string {
  return JSON.stringify(RunCreate$outboundSchema.parse(runCreate));
}

export function runCreateFromJSON(
  jsonString: string,
): SafeParseResult<RunCreate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RunCreate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunCreate' from JSON`,
  );
}
