/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const RunStatus = {
  Running: "Running",
  Succeeded: "Succeeded",
  Failed: "Failed",
} as const;
export type RunStatus = ClosedEnum<typeof RunStatus>;

/** @internal */
export const RunStatus$inboundSchema: z.ZodNativeEnum<typeof RunStatus> = z
  .nativeEnum(RunStatus);

/** @internal */
export const RunStatus$outboundSchema: z.ZodNativeEnum<typeof RunStatus> =
  RunStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunStatus$ {
  /** @deprecated use `RunStatus$inboundSchema` instead. */
  export const inboundSchema = RunStatus$inboundSchema;
  /** @deprecated use `RunStatus$outboundSchema` instead. */
  export const outboundSchema = RunStatus$outboundSchema;
}
