/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ThreadCreate = {
  title?: string | null | undefined;
};

/** @internal */
export const ThreadCreate$inboundSchema: z.ZodType<
  ThreadCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  title: z.nullable(z.string()).optional(),
});

/** @internal */
export type ThreadCreate$Outbound = {
  title?: string | null | undefined;
};

/** @internal */
export const ThreadCreate$outboundSchema: z.ZodType<
  ThreadCreate$Outbound,
  z.ZodTypeDef,
  ThreadCreate
> = z.object({
  title: z.nullable(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ThreadCreate$ {
  /** @deprecated use `ThreadCreate$inboundSchema` instead. */
  export const inboundSchema = ThreadCreate$inboundSchema;
  /** @deprecated use `ThreadCreate$outboundSchema` instead. */
  export const outboundSchema = ThreadCreate$outboundSchema;
  /** @deprecated use `ThreadCreate$Outbound` instead. */
  export type Outbound = ThreadCreate$Outbound;
}

export function threadCreateToJSON(threadCreate: ThreadCreate): string {
  return JSON.stringify(ThreadCreate$outboundSchema.parse(threadCreate));
}

export function threadCreateFromJSON(
  jsonString: string,
): SafeParseResult<ThreadCreate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreadCreate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreadCreate' from JSON`,
  );
}
