/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ThreadRun = {
  input: string;
};

/** @internal */
export const ThreadRun$inboundSchema: z.ZodType<
  ThreadRun,
  z.ZodTypeDef,
  unknown
> = z.object({
  input: z.string(),
});

/** @internal */
export type ThreadRun$Outbound = {
  input: string;
};

/** @internal */
export const ThreadRun$outboundSchema: z.ZodType<
  ThreadRun$Outbound,
  z.ZodTypeDef,
  ThreadRun
> = z.object({
  input: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ThreadRun$ {
  /** @deprecated use `ThreadRun$inboundSchema` instead. */
  export const inboundSchema = ThreadRun$inboundSchema;
  /** @deprecated use `ThreadRun$outboundSchema` instead. */
  export const outboundSchema = ThreadRun$outboundSchema;
  /** @deprecated use `ThreadRun$Outbound` instead. */
  export type Outbound = ThreadRun$Outbound;
}

export function threadRunToJSON(threadRun: ThreadRun): string {
  return JSON.stringify(ThreadRun$outboundSchema.parse(threadRun));
}

export function threadRunFromJSON(
  jsonString: string,
): SafeParseResult<ThreadRun, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreadRun$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreadRun' from JSON`,
  );
}
