/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type Thread = {
  accountId: string;
  createdAt: Date;
  id: string;
  title?: string | null | undefined;
};

/** @internal */
export const Thread$inboundSchema: z.ZodType<Thread, z.ZodTypeDef, unknown> = z
  .object({
    account_id: z.string(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    id: z.string(),
    title: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "account_id": "accountId",
      "created_at": "createdAt",
    });
  });

/** @internal */
export type Thread$Outbound = {
  account_id: string;
  created_at: string;
  id: string;
  title?: string | null | undefined;
};

/** @internal */
export const Thread$outboundSchema: z.ZodType<
  Thread$Outbound,
  z.ZodTypeDef,
  Thread
> = z.object({
  accountId: z.string(),
  createdAt: z.date().transform(v => v.toISOString()),
  id: z.string(),
  title: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    accountId: "account_id",
    createdAt: "created_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Thread$ {
  /** @deprecated use `Thread$inboundSchema` instead. */
  export const inboundSchema = Thread$inboundSchema;
  /** @deprecated use `Thread$outboundSchema` instead. */
  export const outboundSchema = Thread$outboundSchema;
  /** @deprecated use `Thread$Outbound` instead. */
  export type Outbound = Thread$Outbound;
}
