/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { convertsConvertsCreate } from "../funcs/convertsConvertsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Converts extends ClientSDK {
  async convertsCreate(
    request: components.ConvertCreate,
    options?: RequestOptions,
  ): Promise<components.FileT> {
    return unwrapAsync(convertsConvertsCreate(
      this,
      request,
      options,
    ));
  }
}
