/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { threadsThreadsCreate } from "../funcs/threadsThreadsCreate.js";
import { threadsThreadsDelete } from "../funcs/threadsThreadsDelete.js";
import { threadsThreadsGet } from "../funcs/threadsThreadsGet.js";
import { threadsThreadsList } from "../funcs/threadsThreadsList.js";
import { threadsThreadsRun } from "../funcs/threadsThreadsRun.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Threads extends ClientSDK {
  async threadsList(
    options?: RequestOptions,
  ): Promise<Array<components.Thread>> {
    return unwrapAsync(threadsThreadsList(
      this,
      options,
    ));
  }

  async threadsCreate(
    request: components.ThreadCreate,
    options?: RequestOptions,
  ): Promise<components.Thread> {
    return unwrapAsync(threadsThreadsCreate(
      this,
      request,
      options,
    ));
  }

  async threadsGet(
    request: operations.ThreadsGetRequest,
    options?: RequestOptions,
  ): Promise<components.Thread> {
    return unwrapAsync(threadsThreadsGet(
      this,
      request,
      options,
    ));
  }

  async threadsDelete(
    request: operations.ThreadsDeleteRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(threadsThreadsDelete(
      this,
      request,
      options,
    ));
  }

  async threadsRun(
    request: operations.ThreadsRunRequest,
    options?: RequestOptions,
  ): Promise<string> {
    return unwrapAsync(threadsThreadsRun(
      this,
      request,
      options,
    ));
  }
}
