/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { blobLikeSchema } from "../../types/blobs.js";
import * as z from "zod";

export type Data = {
    fileName: string;
    content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Buffer;
};

export type FileUpload = {
    data: Data | Blob;
};

/** @internal */
export const Data$inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z.object({
    fileName: z.string(),
    content: z.union([
        z.instanceof(ReadableStream<Uint8Array>),
        z.instanceof(Blob),
        z.instanceof(ArrayBuffer),
        z.instanceof(Buffer),
    ]),
});

/** @internal */
export type Data$Outbound = {
    fileName: string;
    content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Buffer;
};

/** @internal */
export const Data$outboundSchema: z.ZodType<Data$Outbound, z.ZodTypeDef, Data> = z.object({
    fileName: z.string(),
    content: z.union([
        z.instanceof(ReadableStream<Uint8Array>),
        z.instanceof(Blob),
        z.instanceof(ArrayBuffer),
        z.instanceof(Buffer),
    ]),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Data$ {
    /** @deprecated use `Data$inboundSchema` instead. */
    export const inboundSchema = Data$inboundSchema;
    /** @deprecated use `Data$outboundSchema` instead. */
    export const outboundSchema = Data$outboundSchema;
    /** @deprecated use `Data$Outbound` instead. */
    export type Outbound = Data$Outbound;
}

/** @internal */
export const FileUpload$inboundSchema: z.ZodType<FileUpload, z.ZodTypeDef, unknown> = z.object({
    data: z.lazy(() => Data$inboundSchema),
});

/** @internal */
export type FileUpload$Outbound = {
    data: Data$Outbound | Blob;
};

/** @internal */
export const FileUpload$outboundSchema: z.ZodType<FileUpload$Outbound, z.ZodTypeDef, FileUpload> =
    z.object({
        data: z.lazy(() => Data$outboundSchema).or(blobLikeSchema),
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileUpload$ {
    /** @deprecated use `FileUpload$inboundSchema` instead. */
    export const inboundSchema = FileUpload$inboundSchema;
    /** @deprecated use `FileUpload$outboundSchema` instead. */
    export const outboundSchema = FileUpload$outboundSchema;
    /** @deprecated use `FileUpload$Outbound` instead. */
    export type Outbound = FileUpload$Outbound;
}
