/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type RunCreate = {
    inputFileId: string;
    targetLanguage: string;
};

/** @internal */
export const RunCreate$inboundSchema: z.ZodType<RunCreate, z.ZodTypeDef, unknown> = z
    .object({
        input_file_id: z.string(),
        target_language: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            input_file_id: "inputFileId",
            target_language: "targetLanguage",
        });
    });

/** @internal */
export type RunCreate$Outbound = {
    input_file_id: string;
    target_language: string;
};

/** @internal */
export const RunCreate$outboundSchema: z.ZodType<RunCreate$Outbound, z.ZodTypeDef, RunCreate> = z
    .object({
        inputFileId: z.string(),
        targetLanguage: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            inputFileId: "input_file_id",
            targetLanguage: "target_language",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunCreate$ {
    /** @deprecated use `RunCreate$inboundSchema` instead. */
    export const inboundSchema = RunCreate$inboundSchema;
    /** @deprecated use `RunCreate$outboundSchema` instead. */
    export const outboundSchema = RunCreate$outboundSchema;
    /** @deprecated use `RunCreate$Outbound` instead. */
    export type Outbound = RunCreate$Outbound;
}
