workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Edgen-OAS:
        inputs:
            - location: ../../../../backend/server/docs/openapi.yml
        registry:
            location: registry.speakeasyapi.dev/edgenai/edgenai/edgen-oas
targets:
    edgen:
        target: typescript
        source: Edgen-OAS
