/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
    LLMConfig,
    LLMConfig$inboundSchema,
    LLMConfig$Outbound,
    LLMConfig$outboundSchema,
} from "./llmconfig.js";
import * as z from "zod";

export type AgentConfigInputIsTerminationMsg = boolean | string;

export const AgentConfigInputCodeExecutionConfigTypes = {
    Local: "local",
    Docker: "docker",
    None: "none",
} as const;
export type AgentConfigInputCodeExecutionConfigTypes = ClosedEnum<
    typeof AgentConfigInputCodeExecutionConfigTypes
>;

export type AgentConfigInputLlmConfig = LLMConfig | boolean;

export type AgentConfigInputMessages = {};

export type AgentConfigInputAllowRepeatSpeaker = boolean | Array<AgentConfigInput>;

export type AgentConfigInput = {
    name?: string | null | undefined;
    humanInputMode?: string | undefined;
    maxConsecutiveAutoReply?: number | undefined;
    systemMessage?: string | null | undefined;
    isTerminationMsg?: boolean | string | null | undefined;
    codeExecutionConfig?: AgentConfigInputCodeExecutionConfigTypes | undefined;
    defaultAutoReply?: string | null | undefined;
    description?: string | null | undefined;
    llmConfig?: LLMConfig | boolean | null | undefined;
    adminName?: string | null | undefined;
    messages?: Array<AgentConfigInputMessages> | null | undefined;
    maxRound?: number | null | undefined;
    speakerSelectionMethod?: string | null | undefined;
    allowRepeatSpeaker?: boolean | Array<AgentConfigInput> | null | undefined;
};

/** @internal */
export const AgentConfigInputIsTerminationMsg$inboundSchema: z.ZodType<
    AgentConfigInputIsTerminationMsg,
    z.ZodTypeDef,
    unknown
> = z.union([z.boolean(), z.string()]);

/** @internal */
export type AgentConfigInputIsTerminationMsg$Outbound = boolean | string;

/** @internal */
export const AgentConfigInputIsTerminationMsg$outboundSchema: z.ZodType<
    AgentConfigInputIsTerminationMsg$Outbound,
    z.ZodTypeDef,
    AgentConfigInputIsTerminationMsg
> = z.union([z.boolean(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentConfigInputIsTerminationMsg$ {
    /** @deprecated use `AgentConfigInputIsTerminationMsg$inboundSchema` instead. */
    export const inboundSchema = AgentConfigInputIsTerminationMsg$inboundSchema;
    /** @deprecated use `AgentConfigInputIsTerminationMsg$outboundSchema` instead. */
    export const outboundSchema = AgentConfigInputIsTerminationMsg$outboundSchema;
    /** @deprecated use `AgentConfigInputIsTerminationMsg$Outbound` instead. */
    export type Outbound = AgentConfigInputIsTerminationMsg$Outbound;
}

/** @internal */
export const AgentConfigInputCodeExecutionConfigTypes$inboundSchema: z.ZodNativeEnum<
    typeof AgentConfigInputCodeExecutionConfigTypes
> = z.nativeEnum(AgentConfigInputCodeExecutionConfigTypes);

/** @internal */
export const AgentConfigInputCodeExecutionConfigTypes$outboundSchema: z.ZodNativeEnum<
    typeof AgentConfigInputCodeExecutionConfigTypes
> = AgentConfigInputCodeExecutionConfigTypes$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentConfigInputCodeExecutionConfigTypes$ {
    /** @deprecated use `AgentConfigInputCodeExecutionConfigTypes$inboundSchema` instead. */
    export const inboundSchema = AgentConfigInputCodeExecutionConfigTypes$inboundSchema;
    /** @deprecated use `AgentConfigInputCodeExecutionConfigTypes$outboundSchema` instead. */
    export const outboundSchema = AgentConfigInputCodeExecutionConfigTypes$outboundSchema;
}

/** @internal */
export const AgentConfigInputLlmConfig$inboundSchema: z.ZodType<
    AgentConfigInputLlmConfig,
    z.ZodTypeDef,
    unknown
> = z.union([LLMConfig$inboundSchema, z.boolean()]);

/** @internal */
export type AgentConfigInputLlmConfig$Outbound = LLMConfig$Outbound | boolean;

/** @internal */
export const AgentConfigInputLlmConfig$outboundSchema: z.ZodType<
    AgentConfigInputLlmConfig$Outbound,
    z.ZodTypeDef,
    AgentConfigInputLlmConfig
> = z.union([LLMConfig$outboundSchema, z.boolean()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentConfigInputLlmConfig$ {
    /** @deprecated use `AgentConfigInputLlmConfig$inboundSchema` instead. */
    export const inboundSchema = AgentConfigInputLlmConfig$inboundSchema;
    /** @deprecated use `AgentConfigInputLlmConfig$outboundSchema` instead. */
    export const outboundSchema = AgentConfigInputLlmConfig$outboundSchema;
    /** @deprecated use `AgentConfigInputLlmConfig$Outbound` instead. */
    export type Outbound = AgentConfigInputLlmConfig$Outbound;
}

/** @internal */
export const AgentConfigInputMessages$inboundSchema: z.ZodType<
    AgentConfigInputMessages,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type AgentConfigInputMessages$Outbound = {};

/** @internal */
export const AgentConfigInputMessages$outboundSchema: z.ZodType<
    AgentConfigInputMessages$Outbound,
    z.ZodTypeDef,
    AgentConfigInputMessages
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentConfigInputMessages$ {
    /** @deprecated use `AgentConfigInputMessages$inboundSchema` instead. */
    export const inboundSchema = AgentConfigInputMessages$inboundSchema;
    /** @deprecated use `AgentConfigInputMessages$outboundSchema` instead. */
    export const outboundSchema = AgentConfigInputMessages$outboundSchema;
    /** @deprecated use `AgentConfigInputMessages$Outbound` instead. */
    export type Outbound = AgentConfigInputMessages$Outbound;
}

/** @internal */
export const AgentConfigInputAllowRepeatSpeaker$inboundSchema: z.ZodType<
    AgentConfigInputAllowRepeatSpeaker,
    z.ZodTypeDef,
    unknown
> = z.union([z.boolean(), z.array(z.lazy(() => AgentConfigInput$inboundSchema))]);

/** @internal */
export type AgentConfigInputAllowRepeatSpeaker$Outbound =
    | boolean
    | Array<AgentConfigInput$Outbound>;

/** @internal */
export const AgentConfigInputAllowRepeatSpeaker$outboundSchema: z.ZodType<
    AgentConfigInputAllowRepeatSpeaker$Outbound,
    z.ZodTypeDef,
    AgentConfigInputAllowRepeatSpeaker
> = z.union([z.boolean(), z.array(z.lazy(() => AgentConfigInput$outboundSchema))]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentConfigInputAllowRepeatSpeaker$ {
    /** @deprecated use `AgentConfigInputAllowRepeatSpeaker$inboundSchema` instead. */
    export const inboundSchema = AgentConfigInputAllowRepeatSpeaker$inboundSchema;
    /** @deprecated use `AgentConfigInputAllowRepeatSpeaker$outboundSchema` instead. */
    export const outboundSchema = AgentConfigInputAllowRepeatSpeaker$outboundSchema;
    /** @deprecated use `AgentConfigInputAllowRepeatSpeaker$Outbound` instead. */
    export type Outbound = AgentConfigInputAllowRepeatSpeaker$Outbound;
}

/** @internal */
export const AgentConfigInput$inboundSchema: z.ZodType<AgentConfigInput, z.ZodTypeDef, unknown> = z
    .object({
        name: z.nullable(z.string()).optional(),
        human_input_mode: z.string().default("NEVER"),
        max_consecutive_auto_reply: z.number().int().default(10),
        system_message: z.nullable(z.string()).optional(),
        is_termination_msg: z.nullable(z.union([z.boolean(), z.string()])).optional(),
        code_execution_config:
            AgentConfigInputCodeExecutionConfigTypes$inboundSchema.default("local"),
        default_auto_reply: z.nullable(z.string()).optional(),
        description: z.nullable(z.string()).optional(),
        llm_config: z.nullable(z.union([LLMConfig$inboundSchema, z.boolean()])).optional(),
        admin_name: z.nullable(z.string()).optional(),
        messages: z
            .nullable(z.array(z.lazy(() => AgentConfigInputMessages$inboundSchema)))
            .optional(),
        max_round: z.nullable(z.number().int()).optional(),
        speaker_selection_method: z.nullable(z.string()).optional(),
        allow_repeat_speaker: z
            .nullable(z.union([z.boolean(), z.array(z.lazy(() => AgentConfigInput$inboundSchema))]))
            .optional(),
    })
    .transform((v) => {
        return remap$(v, {
            human_input_mode: "humanInputMode",
            max_consecutive_auto_reply: "maxConsecutiveAutoReply",
            system_message: "systemMessage",
            is_termination_msg: "isTerminationMsg",
            code_execution_config: "codeExecutionConfig",
            default_auto_reply: "defaultAutoReply",
            llm_config: "llmConfig",
            admin_name: "adminName",
            max_round: "maxRound",
            speaker_selection_method: "speakerSelectionMethod",
            allow_repeat_speaker: "allowRepeatSpeaker",
        });
    });

/** @internal */
export type AgentConfigInput$Outbound = {
    name?: string | null | undefined;
    human_input_mode: string;
    max_consecutive_auto_reply: number;
    system_message?: string | null | undefined;
    is_termination_msg?: boolean | string | null | undefined;
    code_execution_config: string;
    default_auto_reply?: string | null | undefined;
    description?: string | null | undefined;
    llm_config?: LLMConfig$Outbound | boolean | null | undefined;
    admin_name?: string | null | undefined;
    messages?: Array<AgentConfigInputMessages$Outbound> | null | undefined;
    max_round?: number | null | undefined;
    speaker_selection_method?: string | null | undefined;
    allow_repeat_speaker?: boolean | Array<AgentConfigInput$Outbound> | null | undefined;
};

/** @internal */
export const AgentConfigInput$outboundSchema: z.ZodType<
    AgentConfigInput$Outbound,
    z.ZodTypeDef,
    AgentConfigInput
> = z
    .object({
        name: z.nullable(z.string()).optional(),
        humanInputMode: z.string().default("NEVER"),
        maxConsecutiveAutoReply: z.number().int().default(10),
        systemMessage: z.nullable(z.string()).optional(),
        isTerminationMsg: z.nullable(z.union([z.boolean(), z.string()])).optional(),
        codeExecutionConfig:
            AgentConfigInputCodeExecutionConfigTypes$outboundSchema.default("local"),
        defaultAutoReply: z.nullable(z.string()).optional(),
        description: z.nullable(z.string()).optional(),
        llmConfig: z.nullable(z.union([LLMConfig$outboundSchema, z.boolean()])).optional(),
        adminName: z.nullable(z.string()).optional(),
        messages: z
            .nullable(z.array(z.lazy(() => AgentConfigInputMessages$outboundSchema)))
            .optional(),
        maxRound: z.nullable(z.number().int()).optional(),
        speakerSelectionMethod: z.nullable(z.string()).optional(),
        allowRepeatSpeaker: z
            .nullable(
                z.union([z.boolean(), z.array(z.lazy(() => AgentConfigInput$outboundSchema))])
            )
            .optional(),
    })
    .transform((v) => {
        return remap$(v, {
            humanInputMode: "human_input_mode",
            maxConsecutiveAutoReply: "max_consecutive_auto_reply",
            systemMessage: "system_message",
            isTerminationMsg: "is_termination_msg",
            codeExecutionConfig: "code_execution_config",
            defaultAutoReply: "default_auto_reply",
            llmConfig: "llm_config",
            adminName: "admin_name",
            maxRound: "max_round",
            speakerSelectionMethod: "speaker_selection_method",
            allowRepeatSpeaker: "allow_repeat_speaker",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentConfigInput$ {
    /** @deprecated use `AgentConfigInput$inboundSchema` instead. */
    export const inboundSchema = AgentConfigInput$inboundSchema;
    /** @deprecated use `AgentConfigInput$outboundSchema` instead. */
    export const outboundSchema = AgentConfigInput$outboundSchema;
    /** @deprecated use `AgentConfigInput$Outbound` instead. */
    export type Outbound = AgentConfigInput$Outbound;
}
