/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import {
    AgentConfigInput,
    AgentConfigInput$inboundSchema,
    AgentConfigInput$Outbound,
    AgentConfigInput$outboundSchema,
} from "./agentconfiginput.js";
import { AgentType, AgentType$inboundSchema, AgentType$outboundSchema } from "./agenttype.js";
import {
    RetrieveAgentConfig,
    RetrieveAgentConfig$inboundSchema,
    RetrieveAgentConfig$Outbound,
    RetrieveAgentConfig$outboundSchema,
} from "./retrieveagentconfig.js";
import * as z from "zod";

export type AgentCreate = {
    id?: number | null | undefined;
    type: AgentType;
    config: AgentConfigInput;
    retrieveConfig?: RetrieveAgentConfig | null | undefined;
};

/** @internal */
export const AgentCreate$inboundSchema: z.ZodType<AgentCreate, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        type: AgentType$inboundSchema,
        config: AgentConfigInput$inboundSchema,
        retrieve_config: z.nullable(RetrieveAgentConfig$inboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            retrieve_config: "retrieveConfig",
        });
    });

/** @internal */
export type AgentCreate$Outbound = {
    id?: number | null | undefined;
    type: string;
    config: AgentConfigInput$Outbound;
    retrieve_config?: RetrieveAgentConfig$Outbound | null | undefined;
};

/** @internal */
export const AgentCreate$outboundSchema: z.ZodType<
    AgentCreate$Outbound,
    z.ZodTypeDef,
    AgentCreate
> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        type: AgentType$outboundSchema,
        config: AgentConfigInput$outboundSchema,
        retrieveConfig: z.nullable(RetrieveAgentConfig$outboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            retrieveConfig: "retrieve_config",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentCreate$ {
    /** @deprecated use `AgentCreate$inboundSchema` instead. */
    export const inboundSchema = AgentCreate$inboundSchema;
    /** @deprecated use `AgentCreate$outboundSchema` instead. */
    export const outboundSchema = AgentCreate$outboundSchema;
    /** @deprecated use `AgentCreate$Outbound` instead. */
    export type Outbound = AgentCreate$Outbound;
}
