/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const AgentType = {
    Assistant: "assistant",
    Userproxy: "userproxy",
    Groupchat: "groupchat",
    Retriever: "retriever",
    Retrieverassistant: "retrieverassistant",
} as const;
export type AgentType = ClosedEnum<typeof AgentType>;

/** @internal */
export const AgentType$inboundSchema: z.ZodNativeEnum<typeof AgentType> = z.nativeEnum(AgentType);

/** @internal */
export const AgentType$outboundSchema: z.ZodNativeEnum<typeof AgentType> = AgentType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentType$ {
    /** @deprecated use `AgentType$inboundSchema` instead. */
    export const inboundSchema = AgentType$inboundSchema;
    /** @deprecated use `AgentType$outboundSchema` instead. */
    export const outboundSchema = AgentType$outboundSchema;
}
