/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
    AgentConfigOutput,
    AgentConfigOutput$inboundSchema,
    AgentConfigOutput$Outbound,
    AgentConfigOutput$outboundSchema,
} from "./agentconfigoutput.js";
import {
    RetrieveAgentConfig,
    RetrieveAgentConfig$inboundSchema,
    RetrieveAgentConfig$Outbound,
    RetrieveAgentConfig$outboundSchema,
} from "./retrieveagentconfig.js";
import * as z from "zod";

export const AgentAgentType = {
    Assistant: "assistant",
    Userproxy: "userproxy",
    Groupchat: "groupchat",
    Retriever: "retriever",
    Retrieverassistant: "retrieverassistant",
} as const;
export type AgentAgentType = ClosedEnum<typeof AgentAgentType>;

export type Agent = {
    id?: number | null | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    type?: AgentAgentType | undefined;
    config?: AgentConfigOutput | undefined;
    retrieveConfig?: RetrieveAgentConfig | null | undefined;
    owner: string | null;
    isPublic?: boolean | null | undefined;
};

/** @internal */
export const AgentAgentType$inboundSchema: z.ZodNativeEnum<typeof AgentAgentType> =
    z.nativeEnum(AgentAgentType);

/** @internal */
export const AgentAgentType$outboundSchema: z.ZodNativeEnum<typeof AgentAgentType> =
    AgentAgentType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentAgentType$ {
    /** @deprecated use `AgentAgentType$inboundSchema` instead. */
    export const inboundSchema = AgentAgentType$inboundSchema;
    /** @deprecated use `AgentAgentType$outboundSchema` instead. */
    export const outboundSchema = AgentAgentType$outboundSchema;
}

/** @internal */
export const Agent$inboundSchema: z.ZodType<Agent, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        created_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        updated_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        type: AgentAgentType$inboundSchema.default("assistant"),
        config: AgentConfigOutput$inboundSchema.optional(),
        retrieve_config: z.nullable(RetrieveAgentConfig$inboundSchema).optional(),
        owner: z.nullable(z.string()),
        is_public: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            created_at: "createdAt",
            updated_at: "updatedAt",
            retrieve_config: "retrieveConfig",
            is_public: "isPublic",
        });
    });

/** @internal */
export type Agent$Outbound = {
    id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    type: string;
    config?: AgentConfigOutput$Outbound | undefined;
    retrieve_config?: RetrieveAgentConfig$Outbound | null | undefined;
    owner: string | null;
    is_public?: boolean | null | undefined;
};

/** @internal */
export const Agent$outboundSchema: z.ZodType<Agent$Outbound, z.ZodTypeDef, Agent> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        createdAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        updatedAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        type: AgentAgentType$outboundSchema.default("assistant"),
        config: AgentConfigOutput$outboundSchema.optional(),
        retrieveConfig: z.nullable(RetrieveAgentConfig$outboundSchema).optional(),
        owner: z.nullable(z.string()),
        isPublic: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            createdAt: "created_at",
            updatedAt: "updated_at",
            retrieveConfig: "retrieve_config",
            isPublic: "is_public",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Agent$ {
    /** @deprecated use `Agent$inboundSchema` instead. */
    export const inboundSchema = Agent$inboundSchema;
    /** @deprecated use `Agent$outboundSchema` instead. */
    export const outboundSchema = Agent$outboundSchema;
    /** @deprecated use `Agent$Outbound` instead. */
    export type Outbound = Agent$Outbound;
}
