/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
    LLMConfig,
    LLMConfig$inboundSchema,
    LLMConfig$Outbound,
    LLMConfig$outboundSchema,
} from "./llmconfig.js";
import * as z from "zod";

export type IsTerminationMsg = boolean | string;

export const CodeExecutionConfigTypes = {
    Local: "local",
    Docker: "docker",
    None: "none",
} as const;
export type CodeExecutionConfigTypes = ClosedEnum<typeof CodeExecutionConfigTypes>;

export type AgentConfigOutputLlmConfig = LLMConfig | boolean;

export type Messages = {};

export type AllowRepeatSpeaker = boolean | Array<AgentConfigOutput>;

export type AgentConfigOutput = {
    name?: string | null | undefined;
    humanInputMode?: string | undefined;
    maxConsecutiveAutoReply?: number | undefined;
    systemMessage?: string | null | undefined;
    isTerminationMsg?: boolean | string | null | undefined;
    codeExecutionConfig?: CodeExecutionConfigTypes | undefined;
    defaultAutoReply?: string | null | undefined;
    description?: string | null | undefined;
    llmConfig?: LLMConfig | boolean | null | undefined;
    adminName?: string | null | undefined;
    messages?: Array<Messages> | null | undefined;
    maxRound?: number | null | undefined;
    speakerSelectionMethod?: string | null | undefined;
    allowRepeatSpeaker?: boolean | Array<AgentConfigOutput> | null | undefined;
};

/** @internal */
export const IsTerminationMsg$inboundSchema: z.ZodType<IsTerminationMsg, z.ZodTypeDef, unknown> =
    z.union([z.boolean(), z.string()]);

/** @internal */
export type IsTerminationMsg$Outbound = boolean | string;

/** @internal */
export const IsTerminationMsg$outboundSchema: z.ZodType<
    IsTerminationMsg$Outbound,
    z.ZodTypeDef,
    IsTerminationMsg
> = z.union([z.boolean(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace IsTerminationMsg$ {
    /** @deprecated use `IsTerminationMsg$inboundSchema` instead. */
    export const inboundSchema = IsTerminationMsg$inboundSchema;
    /** @deprecated use `IsTerminationMsg$outboundSchema` instead. */
    export const outboundSchema = IsTerminationMsg$outboundSchema;
    /** @deprecated use `IsTerminationMsg$Outbound` instead. */
    export type Outbound = IsTerminationMsg$Outbound;
}

/** @internal */
export const CodeExecutionConfigTypes$inboundSchema: z.ZodNativeEnum<
    typeof CodeExecutionConfigTypes
> = z.nativeEnum(CodeExecutionConfigTypes);

/** @internal */
export const CodeExecutionConfigTypes$outboundSchema: z.ZodNativeEnum<
    typeof CodeExecutionConfigTypes
> = CodeExecutionConfigTypes$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CodeExecutionConfigTypes$ {
    /** @deprecated use `CodeExecutionConfigTypes$inboundSchema` instead. */
    export const inboundSchema = CodeExecutionConfigTypes$inboundSchema;
    /** @deprecated use `CodeExecutionConfigTypes$outboundSchema` instead. */
    export const outboundSchema = CodeExecutionConfigTypes$outboundSchema;
}

/** @internal */
export const AgentConfigOutputLlmConfig$inboundSchema: z.ZodType<
    AgentConfigOutputLlmConfig,
    z.ZodTypeDef,
    unknown
> = z.union([LLMConfig$inboundSchema, z.boolean()]);

/** @internal */
export type AgentConfigOutputLlmConfig$Outbound = LLMConfig$Outbound | boolean;

/** @internal */
export const AgentConfigOutputLlmConfig$outboundSchema: z.ZodType<
    AgentConfigOutputLlmConfig$Outbound,
    z.ZodTypeDef,
    AgentConfigOutputLlmConfig
> = z.union([LLMConfig$outboundSchema, z.boolean()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentConfigOutputLlmConfig$ {
    /** @deprecated use `AgentConfigOutputLlmConfig$inboundSchema` instead. */
    export const inboundSchema = AgentConfigOutputLlmConfig$inboundSchema;
    /** @deprecated use `AgentConfigOutputLlmConfig$outboundSchema` instead. */
    export const outboundSchema = AgentConfigOutputLlmConfig$outboundSchema;
    /** @deprecated use `AgentConfigOutputLlmConfig$Outbound` instead. */
    export type Outbound = AgentConfigOutputLlmConfig$Outbound;
}

/** @internal */
export const Messages$inboundSchema: z.ZodType<Messages, z.ZodTypeDef, unknown> = z.object({});

/** @internal */
export type Messages$Outbound = {};

/** @internal */
export const Messages$outboundSchema: z.ZodType<Messages$Outbound, z.ZodTypeDef, Messages> =
    z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Messages$ {
    /** @deprecated use `Messages$inboundSchema` instead. */
    export const inboundSchema = Messages$inboundSchema;
    /** @deprecated use `Messages$outboundSchema` instead. */
    export const outboundSchema = Messages$outboundSchema;
    /** @deprecated use `Messages$Outbound` instead. */
    export type Outbound = Messages$Outbound;
}

/** @internal */
export const AllowRepeatSpeaker$inboundSchema: z.ZodType<
    AllowRepeatSpeaker,
    z.ZodTypeDef,
    unknown
> = z.union([z.boolean(), z.array(z.lazy(() => AgentConfigOutput$inboundSchema))]);

/** @internal */
export type AllowRepeatSpeaker$Outbound = boolean | Array<AgentConfigOutput$Outbound>;

/** @internal */
export const AllowRepeatSpeaker$outboundSchema: z.ZodType<
    AllowRepeatSpeaker$Outbound,
    z.ZodTypeDef,
    AllowRepeatSpeaker
> = z.union([z.boolean(), z.array(z.lazy(() => AgentConfigOutput$outboundSchema))]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AllowRepeatSpeaker$ {
    /** @deprecated use `AllowRepeatSpeaker$inboundSchema` instead. */
    export const inboundSchema = AllowRepeatSpeaker$inboundSchema;
    /** @deprecated use `AllowRepeatSpeaker$outboundSchema` instead. */
    export const outboundSchema = AllowRepeatSpeaker$outboundSchema;
    /** @deprecated use `AllowRepeatSpeaker$Outbound` instead. */
    export type Outbound = AllowRepeatSpeaker$Outbound;
}

/** @internal */
export const AgentConfigOutput$inboundSchema: z.ZodType<AgentConfigOutput, z.ZodTypeDef, unknown> =
    z
        .object({
            name: z.nullable(z.string()).optional(),
            human_input_mode: z.string().default("NEVER"),
            max_consecutive_auto_reply: z.number().int().default(10),
            system_message: z.nullable(z.string()).optional(),
            is_termination_msg: z.nullable(z.union([z.boolean(), z.string()])).optional(),
            code_execution_config: CodeExecutionConfigTypes$inboundSchema.default("local"),
            default_auto_reply: z.nullable(z.string()).optional(),
            description: z.nullable(z.string()).optional(),
            llm_config: z.nullable(z.union([LLMConfig$inboundSchema, z.boolean()])).optional(),
            admin_name: z.nullable(z.string()).optional(),
            messages: z.nullable(z.array(z.lazy(() => Messages$inboundSchema))).optional(),
            max_round: z.nullable(z.number().int()).optional(),
            speaker_selection_method: z.nullable(z.string()).optional(),
            allow_repeat_speaker: z
                .nullable(
                    z.union([z.boolean(), z.array(z.lazy(() => AgentConfigOutput$inboundSchema))])
                )
                .optional(),
        })
        .transform((v) => {
            return remap$(v, {
                human_input_mode: "humanInputMode",
                max_consecutive_auto_reply: "maxConsecutiveAutoReply",
                system_message: "systemMessage",
                is_termination_msg: "isTerminationMsg",
                code_execution_config: "codeExecutionConfig",
                default_auto_reply: "defaultAutoReply",
                llm_config: "llmConfig",
                admin_name: "adminName",
                max_round: "maxRound",
                speaker_selection_method: "speakerSelectionMethod",
                allow_repeat_speaker: "allowRepeatSpeaker",
            });
        });

/** @internal */
export type AgentConfigOutput$Outbound = {
    name?: string | null | undefined;
    human_input_mode: string;
    max_consecutive_auto_reply: number;
    system_message?: string | null | undefined;
    is_termination_msg?: boolean | string | null | undefined;
    code_execution_config: string;
    default_auto_reply?: string | null | undefined;
    description?: string | null | undefined;
    llm_config?: LLMConfig$Outbound | boolean | null | undefined;
    admin_name?: string | null | undefined;
    messages?: Array<Messages$Outbound> | null | undefined;
    max_round?: number | null | undefined;
    speaker_selection_method?: string | null | undefined;
    allow_repeat_speaker?: boolean | Array<AgentConfigOutput$Outbound> | null | undefined;
};

/** @internal */
export const AgentConfigOutput$outboundSchema: z.ZodType<
    AgentConfigOutput$Outbound,
    z.ZodTypeDef,
    AgentConfigOutput
> = z
    .object({
        name: z.nullable(z.string()).optional(),
        humanInputMode: z.string().default("NEVER"),
        maxConsecutiveAutoReply: z.number().int().default(10),
        systemMessage: z.nullable(z.string()).optional(),
        isTerminationMsg: z.nullable(z.union([z.boolean(), z.string()])).optional(),
        codeExecutionConfig: CodeExecutionConfigTypes$outboundSchema.default("local"),
        defaultAutoReply: z.nullable(z.string()).optional(),
        description: z.nullable(z.string()).optional(),
        llmConfig: z.nullable(z.union([LLMConfig$outboundSchema, z.boolean()])).optional(),
        adminName: z.nullable(z.string()).optional(),
        messages: z.nullable(z.array(z.lazy(() => Messages$outboundSchema))).optional(),
        maxRound: z.nullable(z.number().int()).optional(),
        speakerSelectionMethod: z.nullable(z.string()).optional(),
        allowRepeatSpeaker: z
            .nullable(
                z.union([z.boolean(), z.array(z.lazy(() => AgentConfigOutput$outboundSchema))])
            )
            .optional(),
    })
    .transform((v) => {
        return remap$(v, {
            humanInputMode: "human_input_mode",
            maxConsecutiveAutoReply: "max_consecutive_auto_reply",
            systemMessage: "system_message",
            isTerminationMsg: "is_termination_msg",
            codeExecutionConfig: "code_execution_config",
            defaultAutoReply: "default_auto_reply",
            llmConfig: "llm_config",
            adminName: "admin_name",
            maxRound: "max_round",
            speakerSelectionMethod: "speaker_selection_method",
            allowRepeatSpeaker: "allow_repeat_speaker",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentConfigOutput$ {
    /** @deprecated use `AgentConfigOutput$inboundSchema` instead. */
    export const inboundSchema = AgentConfigOutput$inboundSchema;
    /** @deprecated use `AgentConfigOutput$outboundSchema` instead. */
    export const outboundSchema = AgentConfigOutput$outboundSchema;
    /** @deprecated use `AgentConfigOutput$Outbound` instead. */
    export type Outbound = AgentConfigOutput$Outbound;
}
