/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64.js";
import { blobLikeSchema } from "../../types/blobs.js";
import * as z from "zod";

export type BodyFilesUploadFilesSessionIdPostFile = {
    fileName: string;
    content: Uint8Array | string;
};

export type BodyFilesUploadFilesSessionIdPost = {
    file: BodyFilesUploadFilesSessionIdPostFile | Blob;
};

/** @internal */
export const BodyFilesUploadFilesSessionIdPostFile$inboundSchema: z.ZodType<
    BodyFilesUploadFilesSessionIdPostFile,
    z.ZodTypeDef,
    unknown
> = z.object({
    fileName: z.string(),
    content: b64$.zodInbound,
});

/** @internal */
export type BodyFilesUploadFilesSessionIdPostFile$Outbound = {
    fileName: string;
    content: Uint8Array;
};

/** @internal */
export const BodyFilesUploadFilesSessionIdPostFile$outboundSchema: z.ZodType<
    BodyFilesUploadFilesSessionIdPostFile$Outbound,
    z.ZodTypeDef,
    BodyFilesUploadFilesSessionIdPostFile
> = z.object({
    fileName: z.string(),
    content: b64$.zodOutbound,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BodyFilesUploadFilesSessionIdPostFile$ {
    /** @deprecated use `BodyFilesUploadFilesSessionIdPostFile$inboundSchema` instead. */
    export const inboundSchema = BodyFilesUploadFilesSessionIdPostFile$inboundSchema;
    /** @deprecated use `BodyFilesUploadFilesSessionIdPostFile$outboundSchema` instead. */
    export const outboundSchema = BodyFilesUploadFilesSessionIdPostFile$outboundSchema;
    /** @deprecated use `BodyFilesUploadFilesSessionIdPostFile$Outbound` instead. */
    export type Outbound = BodyFilesUploadFilesSessionIdPostFile$Outbound;
}

/** @internal */
export const BodyFilesUploadFilesSessionIdPost$inboundSchema: z.ZodType<
    BodyFilesUploadFilesSessionIdPost,
    z.ZodTypeDef,
    unknown
> = z.object({
    file: z.lazy(() => BodyFilesUploadFilesSessionIdPostFile$inboundSchema),
});

/** @internal */
export type BodyFilesUploadFilesSessionIdPost$Outbound = {
    file: BodyFilesUploadFilesSessionIdPostFile$Outbound | Blob;
};

/** @internal */
export const BodyFilesUploadFilesSessionIdPost$outboundSchema: z.ZodType<
    BodyFilesUploadFilesSessionIdPost$Outbound,
    z.ZodTypeDef,
    BodyFilesUploadFilesSessionIdPost
> = z.object({
    file: z.lazy(() => BodyFilesUploadFilesSessionIdPostFile$outboundSchema).or(blobLikeSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BodyFilesUploadFilesSessionIdPost$ {
    /** @deprecated use `BodyFilesUploadFilesSessionIdPost$inboundSchema` instead. */
    export const inboundSchema = BodyFilesUploadFilesSessionIdPost$inboundSchema;
    /** @deprecated use `BodyFilesUploadFilesSessionIdPost$outboundSchema` instead. */
    export const outboundSchema = BodyFilesUploadFilesSessionIdPost$outboundSchema;
    /** @deprecated use `BodyFilesUploadFilesSessionIdPost$Outbound` instead. */
    export type Outbound = BodyFilesUploadFilesSessionIdPost$Outbound;
}
