/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64.js";
import { blobLikeSchema } from "../../types/blobs.js";
import * as z from "zod";

export type BodyUploadLocalFileLocalfilePostFile = {
    fileName: string;
    content: Uint8Array | string;
};

export type BodyUploadLocalFileLocalfilePost = {
    file: BodyUploadLocalFileLocalfilePostFile | Blob;
};

/** @internal */
export const BodyUploadLocalFileLocalfilePostFile$inboundSchema: z.ZodType<
    BodyUploadLocalFileLocalfilePostFile,
    z.ZodTypeDef,
    unknown
> = z.object({
    fileName: z.string(),
    content: b64$.zodInbound,
});

/** @internal */
export type BodyUploadLocalFileLocalfilePostFile$Outbound = {
    fileName: string;
    content: Uint8Array;
};

/** @internal */
export const BodyUploadLocalFileLocalfilePostFile$outboundSchema: z.ZodType<
    BodyUploadLocalFileLocalfilePostFile$Outbound,
    z.ZodTypeDef,
    BodyUploadLocalFileLocalfilePostFile
> = z.object({
    fileName: z.string(),
    content: b64$.zodOutbound,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BodyUploadLocalFileLocalfilePostFile$ {
    /** @deprecated use `BodyUploadLocalFileLocalfilePostFile$inboundSchema` instead. */
    export const inboundSchema = BodyUploadLocalFileLocalfilePostFile$inboundSchema;
    /** @deprecated use `BodyUploadLocalFileLocalfilePostFile$outboundSchema` instead. */
    export const outboundSchema = BodyUploadLocalFileLocalfilePostFile$outboundSchema;
    /** @deprecated use `BodyUploadLocalFileLocalfilePostFile$Outbound` instead. */
    export type Outbound = BodyUploadLocalFileLocalfilePostFile$Outbound;
}

/** @internal */
export const BodyUploadLocalFileLocalfilePost$inboundSchema: z.ZodType<
    BodyUploadLocalFileLocalfilePost,
    z.ZodTypeDef,
    unknown
> = z.object({
    file: z.lazy(() => BodyUploadLocalFileLocalfilePostFile$inboundSchema),
});

/** @internal */
export type BodyUploadLocalFileLocalfilePost$Outbound = {
    file: BodyUploadLocalFileLocalfilePostFile$Outbound | Blob;
};

/** @internal */
export const BodyUploadLocalFileLocalfilePost$outboundSchema: z.ZodType<
    BodyUploadLocalFileLocalfilePost$Outbound,
    z.ZodTypeDef,
    BodyUploadLocalFileLocalfilePost
> = z.object({
    file: z.lazy(() => BodyUploadLocalFileLocalfilePostFile$outboundSchema).or(blobLikeSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BodyUploadLocalFileLocalfilePost$ {
    /** @deprecated use `BodyUploadLocalFileLocalfilePost$inboundSchema` instead. */
    export const inboundSchema = BodyUploadLocalFileLocalfilePost$inboundSchema;
    /** @deprecated use `BodyUploadLocalFileLocalfilePost$outboundSchema` instead. */
    export const outboundSchema = BodyUploadLocalFileLocalfilePost$outboundSchema;
    /** @deprecated use `BodyUploadLocalFileLocalfilePost$Outbound` instead. */
    export type Outbound = BodyUploadLocalFileLocalfilePost$Outbound;
}
