/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type Connector = {
    id?: number | null | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    name: string;
    type: string;
    owner: string | null;
};

/** @internal */
export const Connector$inboundSchema: z.ZodType<Connector, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        created_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        updated_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        name: z.string(),
        type: z.string(),
        owner: z.nullable(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            created_at: "createdAt",
            updated_at: "updatedAt",
        });
    });

/** @internal */
export type Connector$Outbound = {
    id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    name: string;
    type: string;
    owner: string | null;
};

/** @internal */
export const Connector$outboundSchema: z.ZodType<Connector$Outbound, z.ZodTypeDef, Connector> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        createdAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        updatedAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        name: z.string(),
        type: z.string(),
        owner: z.nullable(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            createdAt: "created_at",
            updatedAt: "updated_at",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Connector$ {
    /** @deprecated use `Connector$inboundSchema` instead. */
    export const inboundSchema = Connector$inboundSchema;
    /** @deprecated use `Connector$outboundSchema` instead. */
    export const outboundSchema = Connector$outboundSchema;
    /** @deprecated use `Connector$Outbound` instead. */
    export type Outbound = Connector$Outbound;
}
