/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ConnectorCreate = {
    id?: number | null | undefined;
    name: string;
    type: string;
};

/** @internal */
export const ConnectorCreate$inboundSchema: z.ZodType<ConnectorCreate, z.ZodTypeDef, unknown> =
    z.object({
        id: z.nullable(z.number().int()).optional(),
        name: z.string(),
        type: z.string(),
    });

/** @internal */
export type ConnectorCreate$Outbound = {
    id?: number | null | undefined;
    name: string;
    type: string;
};

/** @internal */
export const ConnectorCreate$outboundSchema: z.ZodType<
    ConnectorCreate$Outbound,
    z.ZodTypeDef,
    ConnectorCreate
> = z.object({
    id: z.nullable(z.number().int()).optional(),
    name: z.string(),
    type: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectorCreate$ {
    /** @deprecated use `ConnectorCreate$inboundSchema` instead. */
    export const inboundSchema = ConnectorCreate$inboundSchema;
    /** @deprecated use `ConnectorCreate$outboundSchema` instead. */
    export const outboundSchema = ConnectorCreate$outboundSchema;
    /** @deprecated use `ConnectorCreate$Outbound` instead. */
    export type Outbound = ConnectorCreate$Outbound;
}
