/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type KnowledgeBase = {
    id?: number | null | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    name: string;
    owner: string | null;
    isPublic?: boolean | null | undefined;
};

/** @internal */
export const KnowledgeBase$inboundSchema: z.ZodType<KnowledgeBase, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        created_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        updated_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        name: z.string(),
        owner: z.nullable(z.string()),
        is_public: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            created_at: "createdAt",
            updated_at: "updatedAt",
            is_public: "isPublic",
        });
    });

/** @internal */
export type KnowledgeBase$Outbound = {
    id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    name: string;
    owner: string | null;
    is_public?: boolean | null | undefined;
};

/** @internal */
export const KnowledgeBase$outboundSchema: z.ZodType<
    KnowledgeBase$Outbound,
    z.ZodTypeDef,
    KnowledgeBase
> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        createdAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        updatedAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        name: z.string(),
        owner: z.nullable(z.string()),
        isPublic: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            createdAt: "created_at",
            updatedAt: "updated_at",
            isPublic: "is_public",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KnowledgeBase$ {
    /** @deprecated use `KnowledgeBase$inboundSchema` instead. */
    export const inboundSchema = KnowledgeBase$inboundSchema;
    /** @deprecated use `KnowledgeBase$outboundSchema` instead. */
    export const outboundSchema = KnowledgeBase$outboundSchema;
    /** @deprecated use `KnowledgeBase$Outbound` instead. */
    export type Outbound = KnowledgeBase$Outbound;
}
