/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type KnowledgeBaseCreate = {
    id?: number | null | undefined;
    name: string;
};

/** @internal */
export const KnowledgeBaseCreate$inboundSchema: z.ZodType<
    KnowledgeBaseCreate,
    z.ZodTypeDef,
    unknown
> = z.object({
    id: z.nullable(z.number().int()).optional(),
    name: z.string(),
});

/** @internal */
export type KnowledgeBaseCreate$Outbound = {
    id?: number | null | undefined;
    name: string;
};

/** @internal */
export const KnowledgeBaseCreate$outboundSchema: z.ZodType<
    KnowledgeBaseCreate$Outbound,
    z.ZodTypeDef,
    KnowledgeBaseCreate
> = z.object({
    id: z.nullable(z.number().int()).optional(),
    name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KnowledgeBaseCreate$ {
    /** @deprecated use `KnowledgeBaseCreate$inboundSchema` instead. */
    export const inboundSchema = KnowledgeBaseCreate$inboundSchema;
    /** @deprecated use `KnowledgeBaseCreate$outboundSchema` instead. */
    export const outboundSchema = KnowledgeBaseCreate$outboundSchema;
    /** @deprecated use `KnowledgeBaseCreate$Outbound` instead. */
    export type Outbound = KnowledgeBaseCreate$Outbound;
}
