/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type ExtraBody = {};

/**
 * Data model for LLM Config for AutoGen
 */
export type LLMConfig = {
    configList?: Array<any> | undefined;
    model: string;
    temperature?: number | undefined;
    cacheSeed?: number | null | undefined;
    timeout?: number | null | undefined;
    maxTokens?: number | null | undefined;
    extraBody?: ExtraBody | null | undefined;
};

/** @internal */
export const ExtraBody$inboundSchema: z.ZodType<ExtraBody, z.ZodTypeDef, unknown> = z.object({});

/** @internal */
export type ExtraBody$Outbound = {};

/** @internal */
export const ExtraBody$outboundSchema: z.ZodType<ExtraBody$Outbound, z.ZodTypeDef, ExtraBody> =
    z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExtraBody$ {
    /** @deprecated use `ExtraBody$inboundSchema` instead. */
    export const inboundSchema = ExtraBody$inboundSchema;
    /** @deprecated use `ExtraBody$outboundSchema` instead. */
    export const outboundSchema = ExtraBody$outboundSchema;
    /** @deprecated use `ExtraBody$Outbound` instead. */
    export type Outbound = ExtraBody$Outbound;
}

/** @internal */
export const LLMConfig$inboundSchema: z.ZodType<LLMConfig, z.ZodTypeDef, unknown> = z
    .object({
        config_list: z.array(z.any()).optional(),
        model: z.string(),
        temperature: z.number().default(0),
        cache_seed: z.nullable(z.number().int()).optional(),
        timeout: z.nullable(z.number().int()).optional(),
        max_tokens: z.nullable(z.number().int()).optional(),
        extra_body: z.nullable(z.lazy(() => ExtraBody$inboundSchema)).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            config_list: "configList",
            cache_seed: "cacheSeed",
            max_tokens: "maxTokens",
            extra_body: "extraBody",
        });
    });

/** @internal */
export type LLMConfig$Outbound = {
    config_list?: Array<any> | undefined;
    model: string;
    temperature: number;
    cache_seed?: number | null | undefined;
    timeout?: number | null | undefined;
    max_tokens?: number | null | undefined;
    extra_body?: ExtraBody$Outbound | null | undefined;
};

/** @internal */
export const LLMConfig$outboundSchema: z.ZodType<LLMConfig$Outbound, z.ZodTypeDef, LLMConfig> = z
    .object({
        configList: z.array(z.any()).optional(),
        model: z.string(),
        temperature: z.number().default(0),
        cacheSeed: z.nullable(z.number().int()).optional(),
        timeout: z.nullable(z.number().int()).optional(),
        maxTokens: z.nullable(z.number().int()).optional(),
        extraBody: z.nullable(z.lazy(() => ExtraBody$outboundSchema)).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            configList: "config_list",
            cacheSeed: "cache_seed",
            maxTokens: "max_tokens",
            extraBody: "extra_body",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LLMConfig$ {
    /** @deprecated use `LLMConfig$inboundSchema` instead. */
    export const inboundSchema = LLMConfig$inboundSchema;
    /** @deprecated use `LLMConfig$outboundSchema` instead. */
    export const outboundSchema = LLMConfig$outboundSchema;
    /** @deprecated use `LLMConfig$Outbound` instead. */
    export type Outbound = LLMConfig$Outbound;
}
