/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type Message = {
    id?: number | null | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    sender: string;
    receiver: string;
    content: string;
    event?: string | null | undefined;
    sessionId?: number | null | undefined;
    owner?: string | null | undefined;
};

/** @internal */
export const Message$inboundSchema: z.ZodType<Message, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        created_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        updated_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        sender: z.string(),
        receiver: z.string(),
        content: z.string(),
        event: z.nullable(z.string()).optional(),
        session_id: z.nullable(z.number().int()).optional(),
        owner: z.nullable(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            created_at: "createdAt",
            updated_at: "updatedAt",
            session_id: "sessionId",
        });
    });

/** @internal */
export type Message$Outbound = {
    id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    sender: string;
    receiver: string;
    content: string;
    event?: string | null | undefined;
    session_id?: number | null | undefined;
    owner?: string | null | undefined;
};

/** @internal */
export const Message$outboundSchema: z.ZodType<Message$Outbound, z.ZodTypeDef, Message> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        createdAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        updatedAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        sender: z.string(),
        receiver: z.string(),
        content: z.string(),
        event: z.nullable(z.string()).optional(),
        sessionId: z.nullable(z.number().int()).optional(),
        owner: z.nullable(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            createdAt: "created_at",
            updatedAt: "updated_at",
            sessionId: "session_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Message$ {
    /** @deprecated use `Message$inboundSchema` instead. */
    export const inboundSchema = Message$inboundSchema;
    /** @deprecated use `Message$outboundSchema` instead. */
    export const outboundSchema = Message$outboundSchema;
    /** @deprecated use `Message$Outbound` instead. */
    export type Outbound = Message$Outbound;
}
