/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const ModelTypes = {
    OpenAi: "open_ai",
    Google: "google",
    Azure: "azure",
    Aws: "aws",
} as const;
export type ModelTypes = ClosedEnum<typeof ModelTypes>;

export type ModelOutput = {
    id?: number | null | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    model: string;
    name: string;
    apiKey?: string | null | undefined;
    baseUrl?: string | null | undefined;
    apiType?: ModelTypes | undefined;
    apiVersion?: string | null | undefined;
    promptRate: string;
    completionRate: string;
    availability: string;
    creator: string;
    description?: string | null | undefined;
    owner: string | null;
    isPublic?: boolean | null | undefined;
};

/** @internal */
export const ModelTypes$inboundSchema: z.ZodNativeEnum<typeof ModelTypes> =
    z.nativeEnum(ModelTypes);

/** @internal */
export const ModelTypes$outboundSchema: z.ZodNativeEnum<typeof ModelTypes> =
    ModelTypes$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelTypes$ {
    /** @deprecated use `ModelTypes$inboundSchema` instead. */
    export const inboundSchema = ModelTypes$inboundSchema;
    /** @deprecated use `ModelTypes$outboundSchema` instead. */
    export const outboundSchema = ModelTypes$outboundSchema;
}

/** @internal */
export const ModelOutput$inboundSchema: z.ZodType<ModelOutput, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        created_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        updated_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        model: z.string(),
        name: z.string(),
        api_key: z.nullable(z.string()).optional(),
        base_url: z.nullable(z.string()).optional(),
        api_type: ModelTypes$inboundSchema.default("open_ai"),
        api_version: z.nullable(z.string()).optional(),
        prompt_rate: z.string(),
        completion_rate: z.string(),
        availability: z.string(),
        creator: z.string(),
        description: z.nullable(z.string()).optional(),
        owner: z.nullable(z.string()),
        is_public: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            created_at: "createdAt",
            updated_at: "updatedAt",
            api_key: "apiKey",
            base_url: "baseUrl",
            api_type: "apiType",
            api_version: "apiVersion",
            prompt_rate: "promptRate",
            completion_rate: "completionRate",
            is_public: "isPublic",
        });
    });

/** @internal */
export type ModelOutput$Outbound = {
    id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    model: string;
    name: string;
    api_key?: string | null | undefined;
    base_url?: string | null | undefined;
    api_type: string;
    api_version?: string | null | undefined;
    prompt_rate: string;
    completion_rate: string;
    availability: string;
    creator: string;
    description?: string | null | undefined;
    owner: string | null;
    is_public?: boolean | null | undefined;
};

/** @internal */
export const ModelOutput$outboundSchema: z.ZodType<
    ModelOutput$Outbound,
    z.ZodTypeDef,
    ModelOutput
> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        createdAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        updatedAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        model: z.string(),
        name: z.string(),
        apiKey: z.nullable(z.string()).optional(),
        baseUrl: z.nullable(z.string()).optional(),
        apiType: ModelTypes$outboundSchema.default("open_ai"),
        apiVersion: z.nullable(z.string()).optional(),
        promptRate: z.string(),
        completionRate: z.string(),
        availability: z.string(),
        creator: z.string(),
        description: z.nullable(z.string()).optional(),
        owner: z.nullable(z.string()),
        isPublic: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            createdAt: "created_at",
            updatedAt: "updated_at",
            apiKey: "api_key",
            baseUrl: "base_url",
            apiType: "api_type",
            apiVersion: "api_version",
            promptRate: "prompt_rate",
            completionRate: "completion_rate",
            isPublic: "is_public",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelOutput$ {
    /** @deprecated use `ModelOutput$inboundSchema` instead. */
    export const inboundSchema = ModelOutput$inboundSchema;
    /** @deprecated use `ModelOutput$outboundSchema` instead. */
    export const outboundSchema = ModelOutput$outboundSchema;
    /** @deprecated use `ModelOutput$Outbound` instead. */
    export type Outbound = ModelOutput$Outbound;
}
