/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const ModelInputModelTypes = {
    OpenAi: "open_ai",
    Google: "google",
    Azure: "azure",
    Aws: "aws",
} as const;
export type ModelInputModelTypes = ClosedEnum<typeof ModelInputModelTypes>;

export type ModelInputPromptRate = number | string;

export type ModelInputCompletionRate = number | string;

export type ModelInputAvailability = number | string;

export type ModelInput = {
    id?: number | null | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    model: string;
    name: string;
    apiKey?: string | null | undefined;
    baseUrl?: string | null | undefined;
    apiType?: ModelInputModelTypes | undefined;
    apiVersion?: string | null | undefined;
    promptRate: number | string;
    completionRate: number | string;
    availability: number | string;
    creator: string;
    description?: string | null | undefined;
    owner: string | null;
    isPublic?: boolean | null | undefined;
};

/** @internal */
export const ModelInputModelTypes$inboundSchema: z.ZodNativeEnum<typeof ModelInputModelTypes> =
    z.nativeEnum(ModelInputModelTypes);

/** @internal */
export const ModelInputModelTypes$outboundSchema: z.ZodNativeEnum<typeof ModelInputModelTypes> =
    ModelInputModelTypes$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelInputModelTypes$ {
    /** @deprecated use `ModelInputModelTypes$inboundSchema` instead. */
    export const inboundSchema = ModelInputModelTypes$inboundSchema;
    /** @deprecated use `ModelInputModelTypes$outboundSchema` instead. */
    export const outboundSchema = ModelInputModelTypes$outboundSchema;
}

/** @internal */
export const ModelInputPromptRate$inboundSchema: z.ZodType<
    ModelInputPromptRate,
    z.ZodTypeDef,
    unknown
> = z.union([z.number(), z.string()]);

/** @internal */
export type ModelInputPromptRate$Outbound = number | string;

/** @internal */
export const ModelInputPromptRate$outboundSchema: z.ZodType<
    ModelInputPromptRate$Outbound,
    z.ZodTypeDef,
    ModelInputPromptRate
> = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelInputPromptRate$ {
    /** @deprecated use `ModelInputPromptRate$inboundSchema` instead. */
    export const inboundSchema = ModelInputPromptRate$inboundSchema;
    /** @deprecated use `ModelInputPromptRate$outboundSchema` instead. */
    export const outboundSchema = ModelInputPromptRate$outboundSchema;
    /** @deprecated use `ModelInputPromptRate$Outbound` instead. */
    export type Outbound = ModelInputPromptRate$Outbound;
}

/** @internal */
export const ModelInputCompletionRate$inboundSchema: z.ZodType<
    ModelInputCompletionRate,
    z.ZodTypeDef,
    unknown
> = z.union([z.number(), z.string()]);

/** @internal */
export type ModelInputCompletionRate$Outbound = number | string;

/** @internal */
export const ModelInputCompletionRate$outboundSchema: z.ZodType<
    ModelInputCompletionRate$Outbound,
    z.ZodTypeDef,
    ModelInputCompletionRate
> = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelInputCompletionRate$ {
    /** @deprecated use `ModelInputCompletionRate$inboundSchema` instead. */
    export const inboundSchema = ModelInputCompletionRate$inboundSchema;
    /** @deprecated use `ModelInputCompletionRate$outboundSchema` instead. */
    export const outboundSchema = ModelInputCompletionRate$outboundSchema;
    /** @deprecated use `ModelInputCompletionRate$Outbound` instead. */
    export type Outbound = ModelInputCompletionRate$Outbound;
}

/** @internal */
export const ModelInputAvailability$inboundSchema: z.ZodType<
    ModelInputAvailability,
    z.ZodTypeDef,
    unknown
> = z.union([z.number(), z.string()]);

/** @internal */
export type ModelInputAvailability$Outbound = number | string;

/** @internal */
export const ModelInputAvailability$outboundSchema: z.ZodType<
    ModelInputAvailability$Outbound,
    z.ZodTypeDef,
    ModelInputAvailability
> = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelInputAvailability$ {
    /** @deprecated use `ModelInputAvailability$inboundSchema` instead. */
    export const inboundSchema = ModelInputAvailability$inboundSchema;
    /** @deprecated use `ModelInputAvailability$outboundSchema` instead. */
    export const outboundSchema = ModelInputAvailability$outboundSchema;
    /** @deprecated use `ModelInputAvailability$Outbound` instead. */
    export type Outbound = ModelInputAvailability$Outbound;
}

/** @internal */
export const ModelInput$inboundSchema: z.ZodType<ModelInput, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        created_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        updated_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        model: z.string(),
        name: z.string(),
        api_key: z.nullable(z.string()).optional(),
        base_url: z.nullable(z.string()).optional(),
        api_type: ModelInputModelTypes$inboundSchema.default("open_ai"),
        api_version: z.nullable(z.string()).optional(),
        prompt_rate: z.union([z.number(), z.string()]),
        completion_rate: z.union([z.number(), z.string()]),
        availability: z.union([z.number(), z.string()]),
        creator: z.string(),
        description: z.nullable(z.string()).optional(),
        owner: z.nullable(z.string()),
        is_public: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            created_at: "createdAt",
            updated_at: "updatedAt",
            api_key: "apiKey",
            base_url: "baseUrl",
            api_type: "apiType",
            api_version: "apiVersion",
            prompt_rate: "promptRate",
            completion_rate: "completionRate",
            is_public: "isPublic",
        });
    });

/** @internal */
export type ModelInput$Outbound = {
    id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    model: string;
    name: string;
    api_key?: string | null | undefined;
    base_url?: string | null | undefined;
    api_type: string;
    api_version?: string | null | undefined;
    prompt_rate: number | string;
    completion_rate: number | string;
    availability: number | string;
    creator: string;
    description?: string | null | undefined;
    owner: string | null;
    is_public?: boolean | null | undefined;
};

/** @internal */
export const ModelInput$outboundSchema: z.ZodType<ModelInput$Outbound, z.ZodTypeDef, ModelInput> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        createdAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        updatedAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        model: z.string(),
        name: z.string(),
        apiKey: z.nullable(z.string()).optional(),
        baseUrl: z.nullable(z.string()).optional(),
        apiType: ModelInputModelTypes$outboundSchema.default("open_ai"),
        apiVersion: z.nullable(z.string()).optional(),
        promptRate: z.union([z.number(), z.string()]),
        completionRate: z.union([z.number(), z.string()]),
        availability: z.union([z.number(), z.string()]),
        creator: z.string(),
        description: z.nullable(z.string()).optional(),
        owner: z.nullable(z.string()),
        isPublic: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            createdAt: "created_at",
            updatedAt: "updated_at",
            apiKey: "api_key",
            baseUrl: "base_url",
            apiType: "api_type",
            apiVersion: "api_version",
            promptRate: "prompt_rate",
            completionRate: "completion_rate",
            isPublic: "is_public",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelInput$ {
    /** @deprecated use `ModelInput$inboundSchema` instead. */
    export const inboundSchema = ModelInput$inboundSchema;
    /** @deprecated use `ModelInput$outboundSchema` instead. */
    export const outboundSchema = ModelInput$outboundSchema;
    /** @deprecated use `ModelInput$Outbound` instead. */
    export type Outbound = ModelInput$Outbound;
}
