/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const ModelCreateModelTypes = {
    OpenAi: "open_ai",
    Google: "google",
    Azure: "azure",
    Aws: "aws",
} as const;
export type ModelCreateModelTypes = ClosedEnum<typeof ModelCreateModelTypes>;

export type PromptRate = number | string;

export type CompletionRate = number | string;

export type Availability = number | string;

export type ModelCreate = {
    id?: number | null | undefined;
    model: string;
    name: string;
    apiKey?: string | null | undefined;
    baseUrl?: string | null | undefined;
    apiType?: ModelCreateModelTypes | undefined;
    apiVersion?: string | null | undefined;
    promptRate: number | string;
    completionRate: number | string;
    availability: number | string;
    creator: string;
    description?: string | null | undefined;
};

/** @internal */
export const ModelCreateModelTypes$inboundSchema: z.ZodNativeEnum<typeof ModelCreateModelTypes> =
    z.nativeEnum(ModelCreateModelTypes);

/** @internal */
export const ModelCreateModelTypes$outboundSchema: z.ZodNativeEnum<typeof ModelCreateModelTypes> =
    ModelCreateModelTypes$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelCreateModelTypes$ {
    /** @deprecated use `ModelCreateModelTypes$inboundSchema` instead. */
    export const inboundSchema = ModelCreateModelTypes$inboundSchema;
    /** @deprecated use `ModelCreateModelTypes$outboundSchema` instead. */
    export const outboundSchema = ModelCreateModelTypes$outboundSchema;
}

/** @internal */
export const PromptRate$inboundSchema: z.ZodType<PromptRate, z.ZodTypeDef, unknown> = z.union([
    z.number(),
    z.string(),
]);

/** @internal */
export type PromptRate$Outbound = number | string;

/** @internal */
export const PromptRate$outboundSchema: z.ZodType<PromptRate$Outbound, z.ZodTypeDef, PromptRate> =
    z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PromptRate$ {
    /** @deprecated use `PromptRate$inboundSchema` instead. */
    export const inboundSchema = PromptRate$inboundSchema;
    /** @deprecated use `PromptRate$outboundSchema` instead. */
    export const outboundSchema = PromptRate$outboundSchema;
    /** @deprecated use `PromptRate$Outbound` instead. */
    export type Outbound = PromptRate$Outbound;
}

/** @internal */
export const CompletionRate$inboundSchema: z.ZodType<CompletionRate, z.ZodTypeDef, unknown> =
    z.union([z.number(), z.string()]);

/** @internal */
export type CompletionRate$Outbound = number | string;

/** @internal */
export const CompletionRate$outboundSchema: z.ZodType<
    CompletionRate$Outbound,
    z.ZodTypeDef,
    CompletionRate
> = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CompletionRate$ {
    /** @deprecated use `CompletionRate$inboundSchema` instead. */
    export const inboundSchema = CompletionRate$inboundSchema;
    /** @deprecated use `CompletionRate$outboundSchema` instead. */
    export const outboundSchema = CompletionRate$outboundSchema;
    /** @deprecated use `CompletionRate$Outbound` instead. */
    export type Outbound = CompletionRate$Outbound;
}

/** @internal */
export const Availability$inboundSchema: z.ZodType<Availability, z.ZodTypeDef, unknown> = z.union([
    z.number(),
    z.string(),
]);

/** @internal */
export type Availability$Outbound = number | string;

/** @internal */
export const Availability$outboundSchema: z.ZodType<
    Availability$Outbound,
    z.ZodTypeDef,
    Availability
> = z.union([z.number(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Availability$ {
    /** @deprecated use `Availability$inboundSchema` instead. */
    export const inboundSchema = Availability$inboundSchema;
    /** @deprecated use `Availability$outboundSchema` instead. */
    export const outboundSchema = Availability$outboundSchema;
    /** @deprecated use `Availability$Outbound` instead. */
    export type Outbound = Availability$Outbound;
}

/** @internal */
export const ModelCreate$inboundSchema: z.ZodType<ModelCreate, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        model: z.string(),
        name: z.string(),
        api_key: z.nullable(z.string()).optional(),
        base_url: z.nullable(z.string()).optional(),
        api_type: ModelCreateModelTypes$inboundSchema.default("open_ai"),
        api_version: z.nullable(z.string()).optional(),
        prompt_rate: z.union([z.number(), z.string()]),
        completion_rate: z.union([z.number(), z.string()]),
        availability: z.union([z.number(), z.string()]),
        creator: z.string(),
        description: z.nullable(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            api_key: "apiKey",
            base_url: "baseUrl",
            api_type: "apiType",
            api_version: "apiVersion",
            prompt_rate: "promptRate",
            completion_rate: "completionRate",
        });
    });

/** @internal */
export type ModelCreate$Outbound = {
    id?: number | null | undefined;
    model: string;
    name: string;
    api_key?: string | null | undefined;
    base_url?: string | null | undefined;
    api_type: string;
    api_version?: string | null | undefined;
    prompt_rate: number | string;
    completion_rate: number | string;
    availability: number | string;
    creator: string;
    description?: string | null | undefined;
};

/** @internal */
export const ModelCreate$outboundSchema: z.ZodType<
    ModelCreate$Outbound,
    z.ZodTypeDef,
    ModelCreate
> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        model: z.string(),
        name: z.string(),
        apiKey: z.nullable(z.string()).optional(),
        baseUrl: z.nullable(z.string()).optional(),
        apiType: ModelCreateModelTypes$outboundSchema.default("open_ai"),
        apiVersion: z.nullable(z.string()).optional(),
        promptRate: z.union([z.number(), z.string()]),
        completionRate: z.union([z.number(), z.string()]),
        availability: z.union([z.number(), z.string()]),
        creator: z.string(),
        description: z.nullable(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            apiKey: "api_key",
            baseUrl: "base_url",
            apiType: "api_type",
            apiVersion: "api_version",
            promptRate: "prompt_rate",
            completionRate: "completion_rate",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ModelCreate$ {
    /** @deprecated use `ModelCreate$inboundSchema` instead. */
    export const inboundSchema = ModelCreate$inboundSchema;
    /** @deprecated use `ModelCreate$outboundSchema` instead. */
    export const outboundSchema = ModelCreate$outboundSchema;
    /** @deprecated use `ModelCreate$Outbound` instead. */
    export type Outbound = ModelCreate$Outbound;
}
