/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DbConfig = {};

export type RetrieveAgentConfig = {
    task?: string | null | undefined;
    vectorDb?: string | null | undefined;
    dbConfig?: DbConfig | null | undefined;
    docsPath?: string | null | undefined;
    newDocs?: boolean | null | undefined;
    model?: string | null | undefined;
    chunkTokenSize?: number | null | undefined;
    contextMaxTokens?: number | null | undefined;
    chunkMode?: string | null | undefined;
    mustBreakAtEmptyLine?: boolean | null | undefined;
    embeddingModel?: string | null | undefined;
    embeddingFunction?: string | null | undefined;
    customizedPrompt?: string | null | undefined;
    customizedAnswerPrefix?: string | null | undefined;
    updateContext?: boolean | null | undefined;
    collectionName?: string | null | undefined;
    getOrCreate?: boolean | null | undefined;
    overwrite?: boolean | null | undefined;
    customTokenCountFunction?: string | null | undefined;
    customTextSplitFunction?: string | null | undefined;
    customTextTypes?: Array<string> | null | undefined;
    recursive?: boolean | null | undefined;
    distanceThreshold?: number | null | undefined;
};

/** @internal */
export const DbConfig$inboundSchema: z.ZodType<DbConfig, z.ZodTypeDef, unknown> = z.object({});

/** @internal */
export type DbConfig$Outbound = {};

/** @internal */
export const DbConfig$outboundSchema: z.ZodType<DbConfig$Outbound, z.ZodTypeDef, DbConfig> =
    z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DbConfig$ {
    /** @deprecated use `DbConfig$inboundSchema` instead. */
    export const inboundSchema = DbConfig$inboundSchema;
    /** @deprecated use `DbConfig$outboundSchema` instead. */
    export const outboundSchema = DbConfig$outboundSchema;
    /** @deprecated use `DbConfig$Outbound` instead. */
    export type Outbound = DbConfig$Outbound;
}

/** @internal */
export const RetrieveAgentConfig$inboundSchema: z.ZodType<
    RetrieveAgentConfig,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        task: z.nullable(z.string()).optional(),
        vector_db: z.nullable(z.string()).optional(),
        db_config: z.nullable(z.lazy(() => DbConfig$inboundSchema)).optional(),
        docs_path: z.nullable(z.string()).optional(),
        new_docs: z.nullable(z.boolean()).optional(),
        model: z.nullable(z.string()).optional(),
        chunk_token_size: z.nullable(z.number().int()).optional(),
        context_max_tokens: z.nullable(z.number().int()).optional(),
        chunk_mode: z.nullable(z.string()).optional(),
        must_break_at_empty_line: z.nullable(z.boolean()).optional(),
        embedding_model: z.nullable(z.string()).optional(),
        embedding_function: z.nullable(z.string()).optional(),
        customized_prompt: z.nullable(z.string()).optional(),
        customized_answer_prefix: z.nullable(z.string()).optional(),
        update_context: z.nullable(z.boolean()).optional(),
        collection_name: z.nullable(z.string()).optional(),
        get_or_create: z.nullable(z.boolean()).optional(),
        overwrite: z.nullable(z.boolean()).optional(),
        custom_token_count_function: z.nullable(z.string()).optional(),
        custom_text_split_function: z.nullable(z.string()).optional(),
        custom_text_types: z.nullable(z.array(z.string())).optional(),
        recursive: z.nullable(z.boolean()).optional(),
        distance_threshold: z.nullable(z.number()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            vector_db: "vectorDb",
            db_config: "dbConfig",
            docs_path: "docsPath",
            new_docs: "newDocs",
            chunk_token_size: "chunkTokenSize",
            context_max_tokens: "contextMaxTokens",
            chunk_mode: "chunkMode",
            must_break_at_empty_line: "mustBreakAtEmptyLine",
            embedding_model: "embeddingModel",
            embedding_function: "embeddingFunction",
            customized_prompt: "customizedPrompt",
            customized_answer_prefix: "customizedAnswerPrefix",
            update_context: "updateContext",
            collection_name: "collectionName",
            get_or_create: "getOrCreate",
            custom_token_count_function: "customTokenCountFunction",
            custom_text_split_function: "customTextSplitFunction",
            custom_text_types: "customTextTypes",
            distance_threshold: "distanceThreshold",
        });
    });

/** @internal */
export type RetrieveAgentConfig$Outbound = {
    task?: string | null | undefined;
    vector_db?: string | null | undefined;
    db_config?: DbConfig$Outbound | null | undefined;
    docs_path?: string | null | undefined;
    new_docs?: boolean | null | undefined;
    model?: string | null | undefined;
    chunk_token_size?: number | null | undefined;
    context_max_tokens?: number | null | undefined;
    chunk_mode?: string | null | undefined;
    must_break_at_empty_line?: boolean | null | undefined;
    embedding_model?: string | null | undefined;
    embedding_function?: string | null | undefined;
    customized_prompt?: string | null | undefined;
    customized_answer_prefix?: string | null | undefined;
    update_context?: boolean | null | undefined;
    collection_name?: string | null | undefined;
    get_or_create?: boolean | null | undefined;
    overwrite?: boolean | null | undefined;
    custom_token_count_function?: string | null | undefined;
    custom_text_split_function?: string | null | undefined;
    custom_text_types?: Array<string> | null | undefined;
    recursive?: boolean | null | undefined;
    distance_threshold?: number | null | undefined;
};

/** @internal */
export const RetrieveAgentConfig$outboundSchema: z.ZodType<
    RetrieveAgentConfig$Outbound,
    z.ZodTypeDef,
    RetrieveAgentConfig
> = z
    .object({
        task: z.nullable(z.string()).optional(),
        vectorDb: z.nullable(z.string()).optional(),
        dbConfig: z.nullable(z.lazy(() => DbConfig$outboundSchema)).optional(),
        docsPath: z.nullable(z.string()).optional(),
        newDocs: z.nullable(z.boolean()).optional(),
        model: z.nullable(z.string()).optional(),
        chunkTokenSize: z.nullable(z.number().int()).optional(),
        contextMaxTokens: z.nullable(z.number().int()).optional(),
        chunkMode: z.nullable(z.string()).optional(),
        mustBreakAtEmptyLine: z.nullable(z.boolean()).optional(),
        embeddingModel: z.nullable(z.string()).optional(),
        embeddingFunction: z.nullable(z.string()).optional(),
        customizedPrompt: z.nullable(z.string()).optional(),
        customizedAnswerPrefix: z.nullable(z.string()).optional(),
        updateContext: z.nullable(z.boolean()).optional(),
        collectionName: z.nullable(z.string()).optional(),
        getOrCreate: z.nullable(z.boolean()).optional(),
        overwrite: z.nullable(z.boolean()).optional(),
        customTokenCountFunction: z.nullable(z.string()).optional(),
        customTextSplitFunction: z.nullable(z.string()).optional(),
        customTextTypes: z.nullable(z.array(z.string())).optional(),
        recursive: z.nullable(z.boolean()).optional(),
        distanceThreshold: z.nullable(z.number()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            vectorDb: "vector_db",
            dbConfig: "db_config",
            docsPath: "docs_path",
            newDocs: "new_docs",
            chunkTokenSize: "chunk_token_size",
            contextMaxTokens: "context_max_tokens",
            chunkMode: "chunk_mode",
            mustBreakAtEmptyLine: "must_break_at_empty_line",
            embeddingModel: "embedding_model",
            embeddingFunction: "embedding_function",
            customizedPrompt: "customized_prompt",
            customizedAnswerPrefix: "customized_answer_prefix",
            updateContext: "update_context",
            collectionName: "collection_name",
            getOrCreate: "get_or_create",
            customTokenCountFunction: "custom_token_count_function",
            customTextSplitFunction: "custom_text_split_function",
            customTextTypes: "custom_text_types",
            distanceThreshold: "distance_threshold",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RetrieveAgentConfig$ {
    /** @deprecated use `RetrieveAgentConfig$inboundSchema` instead. */
    export const inboundSchema = RetrieveAgentConfig$inboundSchema;
    /** @deprecated use `RetrieveAgentConfig$outboundSchema` instead. */
    export const outboundSchema = RetrieveAgentConfig$outboundSchema;
    /** @deprecated use `RetrieveAgentConfig$Outbound` instead. */
    export type Outbound = RetrieveAgentConfig$Outbound;
}
