/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { FileT, FileT$inboundSchema, FileT$Outbound, FileT$outboundSchema } from "./file.js";
import {
    Message,
    Message$inboundSchema,
    Message$Outbound,
    Message$outboundSchema,
} from "./message.js";
import * as z from "zod";

export type RunWorkflowResponse = {
    summaryMethod: string;
    time: number;
    files: Array<FileT>;
    messages: Array<Message>;
};

/** @internal */
export const RunWorkflowResponse$inboundSchema: z.ZodType<
    RunWorkflowResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        summary_method: z.string(),
        time: z.number(),
        files: z.array(FileT$inboundSchema),
        messages: z.array(Message$inboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            summary_method: "summaryMethod",
        });
    });

/** @internal */
export type RunWorkflowResponse$Outbound = {
    summary_method: string;
    time: number;
    files: Array<FileT$Outbound>;
    messages: Array<Message$Outbound>;
};

/** @internal */
export const RunWorkflowResponse$outboundSchema: z.ZodType<
    RunWorkflowResponse$Outbound,
    z.ZodTypeDef,
    RunWorkflowResponse
> = z
    .object({
        summaryMethod: z.string(),
        time: z.number(),
        files: z.array(FileT$outboundSchema),
        messages: z.array(Message$outboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            summaryMethod: "summary_method",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunWorkflowResponse$ {
    /** @deprecated use `RunWorkflowResponse$inboundSchema` instead. */
    export const inboundSchema = RunWorkflowResponse$inboundSchema;
    /** @deprecated use `RunWorkflowResponse$outboundSchema` instead. */
    export const outboundSchema = RunWorkflowResponse$outboundSchema;
    /** @deprecated use `RunWorkflowResponse$Outbound` instead. */
    export type Outbound = RunWorkflowResponse$Outbound;
}
