/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type RunWorkflowRequest = {
    message: string;
};

/** @internal */
export const RunWorkflowRequest$inboundSchema: z.ZodType<
    RunWorkflowRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    message: z.string(),
});

/** @internal */
export type RunWorkflowRequest$Outbound = {
    message: string;
};

/** @internal */
export const RunWorkflowRequest$outboundSchema: z.ZodType<
    RunWorkflowRequest$Outbound,
    z.ZodTypeDef,
    RunWorkflowRequest
> = z.object({
    message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunWorkflowRequest$ {
    /** @deprecated use `RunWorkflowRequest$inboundSchema` instead. */
    export const inboundSchema = RunWorkflowRequest$inboundSchema;
    /** @deprecated use `RunWorkflowRequest$outboundSchema` instead. */
    export const outboundSchema = RunWorkflowRequest$outboundSchema;
    /** @deprecated use `RunWorkflowRequest$Outbound` instead. */
    export type Outbound = RunWorkflowRequest$Outbound;
}
