/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type Session = {
    id?: number | null | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    workflowId?: number | null | undefined;
    name?: string | null | undefined;
    description?: string | null | undefined;
    owner?: string | null | undefined;
};

/** @internal */
export const Session$inboundSchema: z.ZodType<Session, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        created_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        updated_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        workflow_id: z.nullable(z.number().int()).optional(),
        name: z.nullable(z.string()).optional(),
        description: z.nullable(z.string()).optional(),
        owner: z.nullable(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            created_at: "createdAt",
            updated_at: "updatedAt",
            workflow_id: "workflowId",
        });
    });

/** @internal */
export type Session$Outbound = {
    id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    workflow_id?: number | null | undefined;
    name?: string | null | undefined;
    description?: string | null | undefined;
    owner?: string | null | undefined;
};

/** @internal */
export const Session$outboundSchema: z.ZodType<Session$Outbound, z.ZodTypeDef, Session> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        createdAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        updatedAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        workflowId: z.nullable(z.number().int()).optional(),
        name: z.nullable(z.string()).optional(),
        description: z.nullable(z.string()).optional(),
        owner: z.nullable(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            createdAt: "created_at",
            updatedAt: "updated_at",
            workflowId: "workflow_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Session$ {
    /** @deprecated use `Session$inboundSchema` instead. */
    export const inboundSchema = Session$inboundSchema;
    /** @deprecated use `Session$outboundSchema` instead. */
    export const outboundSchema = Session$outboundSchema;
    /** @deprecated use `Session$Outbound` instead. */
    export type Outbound = Session$Outbound;
}
