/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type SessionCreate = {
    id?: number | null | undefined;
    workflowId?: number | null | undefined;
    name?: string | null | undefined;
    description?: string | null | undefined;
};

/** @internal */
export const SessionCreate$inboundSchema: z.ZodType<SessionCreate, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        workflow_id: z.nullable(z.number().int()).optional(),
        name: z.nullable(z.string()).optional(),
        description: z.nullable(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            workflow_id: "workflowId",
        });
    });

/** @internal */
export type SessionCreate$Outbound = {
    id?: number | null | undefined;
    workflow_id?: number | null | undefined;
    name?: string | null | undefined;
    description?: string | null | undefined;
};

/** @internal */
export const SessionCreate$outboundSchema: z.ZodType<
    SessionCreate$Outbound,
    z.ZodTypeDef,
    SessionCreate
> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        workflowId: z.nullable(z.number().int()).optional(),
        name: z.nullable(z.string()).optional(),
        description: z.nullable(z.string()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            workflowId: "workflow_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SessionCreate$ {
    /** @deprecated use `SessionCreate$inboundSchema` instead. */
    export const inboundSchema = SessionCreate$inboundSchema;
    /** @deprecated use `SessionCreate$outboundSchema` instead. */
    export const outboundSchema = SessionCreate$outboundSchema;
    /** @deprecated use `SessionCreate$Outbound` instead. */
    export type Outbound = SessionCreate$Outbound;
}
