/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type SkillCreateSecrets = {};

export type SkillCreateLibraries = {};

export type SkillCreate = {
    id?: number | null | undefined;
    name: string;
    content: string;
    description?: string | null | undefined;
    secrets?: SkillCreateSecrets | null | undefined;
    libraries?: SkillCreateLibraries | null | undefined;
};

/** @internal */
export const SkillCreateSecrets$inboundSchema: z.ZodType<
    SkillCreateSecrets,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type SkillCreateSecrets$Outbound = {};

/** @internal */
export const SkillCreateSecrets$outboundSchema: z.ZodType<
    SkillCreateSecrets$Outbound,
    z.ZodTypeDef,
    SkillCreateSecrets
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillCreateSecrets$ {
    /** @deprecated use `SkillCreateSecrets$inboundSchema` instead. */
    export const inboundSchema = SkillCreateSecrets$inboundSchema;
    /** @deprecated use `SkillCreateSecrets$outboundSchema` instead. */
    export const outboundSchema = SkillCreateSecrets$outboundSchema;
    /** @deprecated use `SkillCreateSecrets$Outbound` instead. */
    export type Outbound = SkillCreateSecrets$Outbound;
}

/** @internal */
export const SkillCreateLibraries$inboundSchema: z.ZodType<
    SkillCreateLibraries,
    z.ZodTypeDef,
    unknown
> = z.object({});

/** @internal */
export type SkillCreateLibraries$Outbound = {};

/** @internal */
export const SkillCreateLibraries$outboundSchema: z.ZodType<
    SkillCreateLibraries$Outbound,
    z.ZodTypeDef,
    SkillCreateLibraries
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillCreateLibraries$ {
    /** @deprecated use `SkillCreateLibraries$inboundSchema` instead. */
    export const inboundSchema = SkillCreateLibraries$inboundSchema;
    /** @deprecated use `SkillCreateLibraries$outboundSchema` instead. */
    export const outboundSchema = SkillCreateLibraries$outboundSchema;
    /** @deprecated use `SkillCreateLibraries$Outbound` instead. */
    export type Outbound = SkillCreateLibraries$Outbound;
}

/** @internal */
export const SkillCreate$inboundSchema: z.ZodType<SkillCreate, z.ZodTypeDef, unknown> = z.object({
    id: z.nullable(z.number().int()).optional(),
    name: z.string(),
    content: z.string(),
    description: z.nullable(z.string()).optional(),
    secrets: z.nullable(z.lazy(() => SkillCreateSecrets$inboundSchema)).optional(),
    libraries: z.nullable(z.lazy(() => SkillCreateLibraries$inboundSchema)).optional(),
});

/** @internal */
export type SkillCreate$Outbound = {
    id?: number | null | undefined;
    name: string;
    content: string;
    description?: string | null | undefined;
    secrets?: SkillCreateSecrets$Outbound | null | undefined;
    libraries?: SkillCreateLibraries$Outbound | null | undefined;
};

/** @internal */
export const SkillCreate$outboundSchema: z.ZodType<
    SkillCreate$Outbound,
    z.ZodTypeDef,
    SkillCreate
> = z.object({
    id: z.nullable(z.number().int()).optional(),
    name: z.string(),
    content: z.string(),
    description: z.nullable(z.string()).optional(),
    secrets: z.nullable(z.lazy(() => SkillCreateSecrets$outboundSchema)).optional(),
    libraries: z.nullable(z.lazy(() => SkillCreateLibraries$outboundSchema)).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SkillCreate$ {
    /** @deprecated use `SkillCreate$inboundSchema` instead. */
    export const inboundSchema = SkillCreate$inboundSchema;
    /** @deprecated use `SkillCreate$outboundSchema` instead. */
    export const outboundSchema = SkillCreate$outboundSchema;
    /** @deprecated use `SkillCreate$Outbound` instead. */
    export type Outbound = SkillCreate$Outbound;
}
