/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type Secrets = {};

export type Libraries = {};

export type Skill = {
    id?: number | null | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    name: string;
    content: string;
    description?: string | null | undefined;
    secrets?: Secrets | null | undefined;
    libraries?: Libraries | null | undefined;
    owner: string | null;
    isPublic?: boolean | null | undefined;
};

/** @internal */
export const Secrets$inboundSchema: z.ZodType<Secrets, z.ZodTypeDef, unknown> = z.object({});

/** @internal */
export type Secrets$Outbound = {};

/** @internal */
export const Secrets$outboundSchema: z.ZodType<Secrets$Outbound, z.ZodTypeDef, Secrets> = z.object(
    {}
);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Secrets$ {
    /** @deprecated use `Secrets$inboundSchema` instead. */
    export const inboundSchema = Secrets$inboundSchema;
    /** @deprecated use `Secrets$outboundSchema` instead. */
    export const outboundSchema = Secrets$outboundSchema;
    /** @deprecated use `Secrets$Outbound` instead. */
    export type Outbound = Secrets$Outbound;
}

/** @internal */
export const Libraries$inboundSchema: z.ZodType<Libraries, z.ZodTypeDef, unknown> = z.object({});

/** @internal */
export type Libraries$Outbound = {};

/** @internal */
export const Libraries$outboundSchema: z.ZodType<Libraries$Outbound, z.ZodTypeDef, Libraries> =
    z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Libraries$ {
    /** @deprecated use `Libraries$inboundSchema` instead. */
    export const inboundSchema = Libraries$inboundSchema;
    /** @deprecated use `Libraries$outboundSchema` instead. */
    export const outboundSchema = Libraries$outboundSchema;
    /** @deprecated use `Libraries$Outbound` instead. */
    export type Outbound = Libraries$Outbound;
}

/** @internal */
export const Skill$inboundSchema: z.ZodType<Skill, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        created_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        updated_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        name: z.string(),
        content: z.string(),
        description: z.nullable(z.string()).optional(),
        secrets: z.nullable(z.lazy(() => Secrets$inboundSchema)).optional(),
        libraries: z.nullable(z.lazy(() => Libraries$inboundSchema)).optional(),
        owner: z.nullable(z.string()),
        is_public: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            created_at: "createdAt",
            updated_at: "updatedAt",
            is_public: "isPublic",
        });
    });

/** @internal */
export type Skill$Outbound = {
    id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    name: string;
    content: string;
    description?: string | null | undefined;
    secrets?: Secrets$Outbound | null | undefined;
    libraries?: Libraries$Outbound | null | undefined;
    owner: string | null;
    is_public?: boolean | null | undefined;
};

/** @internal */
export const Skill$outboundSchema: z.ZodType<Skill$Outbound, z.ZodTypeDef, Skill> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        createdAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        updatedAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        name: z.string(),
        content: z.string(),
        description: z.nullable(z.string()).optional(),
        secrets: z.nullable(z.lazy(() => Secrets$outboundSchema)).optional(),
        libraries: z.nullable(z.lazy(() => Libraries$outboundSchema)).optional(),
        owner: z.nullable(z.string()),
        isPublic: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            createdAt: "created_at",
            updatedAt: "updated_at",
            isPublic: "is_public",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Skill$ {
    /** @deprecated use `Skill$inboundSchema` instead. */
    export const inboundSchema = Skill$inboundSchema;
    /** @deprecated use `Skill$outboundSchema` instead. */
    export const outboundSchema = Skill$outboundSchema;
    /** @deprecated use `Skill$Outbound` instead. */
    export type Outbound = Skill$Outbound;
}
