/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type TeamMember = {
    team: string;
    account: string;
};

/** @internal */
export const TeamMember$inboundSchema: z.ZodType<TeamMember, z.ZodTypeDef, unknown> = z.object({
    team: z.string(),
    account: z.string(),
});

/** @internal */
export type TeamMember$Outbound = {
    team: string;
    account: string;
};

/** @internal */
export const TeamMember$outboundSchema: z.ZodType<TeamMember$Outbound, z.ZodTypeDef, TeamMember> =
    z.object({
        team: z.string(),
        account: z.string(),
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TeamMember$ {
    /** @deprecated use `TeamMember$inboundSchema` instead. */
    export const inboundSchema = TeamMember$inboundSchema;
    /** @deprecated use `TeamMember$outboundSchema` instead. */
    export const outboundSchema = TeamMember$outboundSchema;
    /** @deprecated use `TeamMember$Outbound` instead. */
    export type Outbound = TeamMember$Outbound;
}
