/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type TeamCreate = {
    id?: string | null | undefined;
    name: string;
    owner?: string | null | undefined;
};

/** @internal */
export const TeamCreate$inboundSchema: z.ZodType<TeamCreate, z.ZodTypeDef, unknown> = z.object({
    id: z.nullable(z.string()).optional(),
    name: z.string(),
    owner: z.nullable(z.string()).optional(),
});

/** @internal */
export type TeamCreate$Outbound = {
    id?: string | null | undefined;
    name: string;
    owner?: string | null | undefined;
};

/** @internal */
export const TeamCreate$outboundSchema: z.ZodType<TeamCreate$Outbound, z.ZodTypeDef, TeamCreate> =
    z.object({
        id: z.nullable(z.string()).optional(),
        name: z.string(),
        owner: z.nullable(z.string()).optional(),
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TeamCreate$ {
    /** @deprecated use `TeamCreate$inboundSchema` instead. */
    export const inboundSchema = TeamCreate$inboundSchema;
    /** @deprecated use `TeamCreate$outboundSchema` instead. */
    export const outboundSchema = TeamCreate$outboundSchema;
    /** @deprecated use `TeamCreate$Outbound` instead. */
    export type Outbound = TeamCreate$Outbound;
}
