/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type Team = {
    id: string | null;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    name: string;
    owner: string | null;
};

/** @internal */
export const Team$inboundSchema: z.ZodType<Team, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.string()),
        created_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        updated_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        name: z.string(),
        owner: z.nullable(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            created_at: "createdAt",
            updated_at: "updatedAt",
        });
    });

/** @internal */
export type Team$Outbound = {
    id: string | null;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    name: string;
    owner: string | null;
};

/** @internal */
export const Team$outboundSchema: z.ZodType<Team$Outbound, z.ZodTypeDef, Team> = z
    .object({
        id: z.nullable(z.string()),
        createdAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        updatedAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        name: z.string(),
        owner: z.nullable(z.string()),
    })
    .transform((v) => {
        return remap$(v, {
            createdAt: "created_at",
            updatedAt: "updated_at",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Team$ {
    /** @deprecated use `Team$inboundSchema` instead. */
    export const inboundSchema = Team$inboundSchema;
    /** @deprecated use `Team$outboundSchema` instead. */
    export const outboundSchema = Team$outboundSchema;
    /** @deprecated use `Team$Outbound` instead. */
    export type Outbound = Team$Outbound;
}
