/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import {
    WorkFlowSummaryMethod,
    WorkFlowSummaryMethod$inboundSchema,
    WorkFlowSummaryMethod$outboundSchema,
} from "./workflowsummarymethod.js";
import {
    WorkFlowType,
    WorkFlowType$inboundSchema,
    WorkFlowType$outboundSchema,
} from "./workflowtype.js";
import * as z from "zod";

export type WorkflowCreate = {
    id?: number | null | undefined;
    name: string;
    description: string;
    type: WorkFlowType;
    summaryMethod?: WorkFlowSummaryMethod | null | undefined;
};

/** @internal */
export const WorkflowCreate$inboundSchema: z.ZodType<WorkflowCreate, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        name: z.string(),
        description: z.string(),
        type: WorkFlowType$inboundSchema,
        summary_method: z.nullable(WorkFlowSummaryMethod$inboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            summary_method: "summaryMethod",
        });
    });

/** @internal */
export type WorkflowCreate$Outbound = {
    id?: number | null | undefined;
    name: string;
    description: string;
    type: string;
    summary_method?: string | null | undefined;
};

/** @internal */
export const WorkflowCreate$outboundSchema: z.ZodType<
    WorkflowCreate$Outbound,
    z.ZodTypeDef,
    WorkflowCreate
> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        name: z.string(),
        description: z.string(),
        type: WorkFlowType$outboundSchema,
        summaryMethod: z.nullable(WorkFlowSummaryMethod$outboundSchema).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            summaryMethod: "summary_method",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowCreate$ {
    /** @deprecated use `WorkflowCreate$inboundSchema` instead. */
    export const inboundSchema = WorkflowCreate$inboundSchema;
    /** @deprecated use `WorkflowCreate$outboundSchema` instead. */
    export const outboundSchema = WorkflowCreate$outboundSchema;
    /** @deprecated use `WorkflowCreate$Outbound` instead. */
    export type Outbound = WorkflowCreate$Outbound;
}
