/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const WorkFlowSummaryMethod = {
    Last: "last",
    None: "none",
    Llm: "llm",
} as const;
export type WorkFlowSummaryMethod = ClosedEnum<typeof WorkFlowSummaryMethod>;

/** @internal */
export const WorkFlowSummaryMethod$inboundSchema: z.ZodNativeEnum<typeof WorkFlowSummaryMethod> =
    z.nativeEnum(WorkFlowSummaryMethod);

/** @internal */
export const WorkFlowSummaryMethod$outboundSchema: z.ZodNativeEnum<typeof WorkFlowSummaryMethod> =
    WorkFlowSummaryMethod$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkFlowSummaryMethod$ {
    /** @deprecated use `WorkFlowSummaryMethod$inboundSchema` instead. */
    export const inboundSchema = WorkFlowSummaryMethod$inboundSchema;
    /** @deprecated use `WorkFlowSummaryMethod$outboundSchema` instead. */
    export const outboundSchema = WorkFlowSummaryMethod$outboundSchema;
}
