/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import {
    WorkFlowSummaryMethod,
    WorkFlowSummaryMethod$inboundSchema,
    WorkFlowSummaryMethod$outboundSchema,
} from "./workflowsummarymethod.js";
import * as z from "zod";

export const WorkflowWorkFlowType = {
    Twoagents: "twoagents",
    Groupchat: "groupchat",
} as const;
export type WorkflowWorkFlowType = ClosedEnum<typeof WorkflowWorkFlowType>;

export type Workflow = {
    id?: number | null | undefined;
    createdAt?: Date | undefined;
    updatedAt?: Date | undefined;
    name: string;
    description: string;
    type?: WorkflowWorkFlowType | undefined;
    summaryMethod?: WorkFlowSummaryMethod | null | undefined;
    owner: string | null;
    isPublic?: boolean | null | undefined;
};

/** @internal */
export const WorkflowWorkFlowType$inboundSchema: z.ZodNativeEnum<typeof WorkflowWorkFlowType> =
    z.nativeEnum(WorkflowWorkFlowType);

/** @internal */
export const WorkflowWorkFlowType$outboundSchema: z.ZodNativeEnum<typeof WorkflowWorkFlowType> =
    WorkflowWorkFlowType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkflowWorkFlowType$ {
    /** @deprecated use `WorkflowWorkFlowType$inboundSchema` instead. */
    export const inboundSchema = WorkflowWorkFlowType$inboundSchema;
    /** @deprecated use `WorkflowWorkFlowType$outboundSchema` instead. */
    export const outboundSchema = WorkflowWorkFlowType$outboundSchema;
}

/** @internal */
export const Workflow$inboundSchema: z.ZodType<Workflow, z.ZodTypeDef, unknown> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        created_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        updated_at: z
            .string()
            .datetime({ offset: true })
            .transform((v) => new Date(v))
            .optional(),
        name: z.string(),
        description: z.string(),
        type: WorkflowWorkFlowType$inboundSchema.default("twoagents"),
        summary_method: z.nullable(WorkFlowSummaryMethod$inboundSchema).optional(),
        owner: z.nullable(z.string()),
        is_public: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            created_at: "createdAt",
            updated_at: "updatedAt",
            summary_method: "summaryMethod",
            is_public: "isPublic",
        });
    });

/** @internal */
export type Workflow$Outbound = {
    id?: number | null | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    name: string;
    description: string;
    type: string;
    summary_method?: string | null | undefined;
    owner: string | null;
    is_public?: boolean | null | undefined;
};

/** @internal */
export const Workflow$outboundSchema: z.ZodType<Workflow$Outbound, z.ZodTypeDef, Workflow> = z
    .object({
        id: z.nullable(z.number().int()).optional(),
        createdAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        updatedAt: z
            .date()
            .transform((v) => v.toISOString())
            .optional(),
        name: z.string(),
        description: z.string(),
        type: WorkflowWorkFlowType$outboundSchema.default("twoagents"),
        summaryMethod: z.nullable(WorkFlowSummaryMethod$outboundSchema).optional(),
        owner: z.nullable(z.string()),
        isPublic: z.nullable(z.boolean()).optional(),
    })
    .transform((v) => {
        return remap$(v, {
            createdAt: "created_at",
            updatedAt: "updated_at",
            summaryMethod: "summary_method",
            isPublic: "is_public",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Workflow$ {
    /** @deprecated use `Workflow$inboundSchema` instead. */
    export const inboundSchema = Workflow$inboundSchema;
    /** @deprecated use `Workflow$outboundSchema` instead. */
    export const outboundSchema = Workflow$outboundSchema;
    /** @deprecated use `Workflow$Outbound` instead. */
    export type Outbound = Workflow$Outbound;
}
