/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const WorkFlowType = {
    Twoagents: "twoagents",
    Groupchat: "groupchat",
} as const;
export type WorkFlowType = ClosedEnum<typeof WorkFlowType>;

/** @internal */
export const WorkFlowType$inboundSchema: z.ZodNativeEnum<typeof WorkFlowType> =
    z.nativeEnum(WorkFlowType);

/** @internal */
export const WorkFlowType$outboundSchema: z.ZodNativeEnum<typeof WorkFlowType> =
    WorkFlowType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkFlowType$ {
    /** @deprecated use `WorkFlowType$inboundSchema` instead. */
    export const inboundSchema = WorkFlowType$inboundSchema;
    /** @deprecated use `WorkFlowType$outboundSchema` instead. */
    export const outboundSchema = WorkFlowType$outboundSchema;
}
