/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { remap as remap$ } from "../../lib/primitives.js";

export type FilesDownloadRequest = {
  /**
   * File ID to download
   */
  fileId: string;
};

export type FilesDownloadResponse = {
  headers: { [k: string]: Array<string> };
  result: Uint8Array | string;
};

/** @internal */
export const FilesDownloadRequest$inboundSchema: z.ZodType<
  FilesDownloadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  file_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "file_id": "fileId",
  });
});

/** @internal */
export type FilesDownloadRequest$Outbound = {
  file_id: string;
};

/** @internal */
export const FilesDownloadRequest$outboundSchema: z.ZodType<
  FilesDownloadRequest$Outbound,
  z.ZodTypeDef,
  FilesDownloadRequest
> = z.object({
  fileId: z.string(),
}).transform((v) => {
  return remap$(v, {
    fileId: "file_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FilesDownloadRequest$ {
  /** @deprecated use `FilesDownloadRequest$inboundSchema` instead. */
  export const inboundSchema = FilesDownloadRequest$inboundSchema;
  /** @deprecated use `FilesDownloadRequest$outboundSchema` instead. */
  export const outboundSchema = FilesDownloadRequest$outboundSchema;
  /** @deprecated use `FilesDownloadRequest$Outbound` instead. */
  export type Outbound = FilesDownloadRequest$Outbound;
}

/** @internal */
export const FilesDownloadResponse$inboundSchema: z.ZodType<
  FilesDownloadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Headers: z.record(z.array(z.string())),
  Result: b64$.zodInbound,
}).transform((v) => {
  return remap$(v, {
    "Headers": "headers",
    "Result": "result",
  });
});

/** @internal */
export type FilesDownloadResponse$Outbound = {
  Headers: { [k: string]: Array<string> };
  Result: Uint8Array;
};

/** @internal */
export const FilesDownloadResponse$outboundSchema: z.ZodType<
  FilesDownloadResponse$Outbound,
  z.ZodTypeDef,
  FilesDownloadResponse
> = z.object({
  headers: z.record(z.array(z.string())),
  result: b64$.zodOutbound,
}).transform((v) => {
  return remap$(v, {
    headers: "Headers",
    result: "Result",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FilesDownloadResponse$ {
  /** @deprecated use `FilesDownloadResponse$inboundSchema` instead. */
  export const inboundSchema = FilesDownloadResponse$inboundSchema;
  /** @deprecated use `FilesDownloadResponse$outboundSchema` instead. */
  export const outboundSchema = FilesDownloadResponse$outboundSchema;
  /** @deprecated use `FilesDownloadResponse$Outbound` instead. */
  export type Outbound = FilesDownloadResponse$Outbound;
}
