/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type MessagesGetRequest = {
  /**
   * The ID of the message to retrieve
   */
  messageId: string;
};

/** @internal */
export const MessagesGetRequest$inboundSchema: z.ZodType<
  MessagesGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  message_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "message_id": "messageId",
  });
});

/** @internal */
export type MessagesGetRequest$Outbound = {
  message_id: string;
};

/** @internal */
export const MessagesGetRequest$outboundSchema: z.ZodType<
  MessagesGetRequest$Outbound,
  z.ZodTypeDef,
  MessagesGetRequest
> = z.object({
  messageId: z.string(),
}).transform((v) => {
  return remap$(v, {
    messageId: "message_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MessagesGetRequest$ {
  /** @deprecated use `MessagesGetRequest$inboundSchema` instead. */
  export const inboundSchema = MessagesGetRequest$inboundSchema;
  /** @deprecated use `MessagesGetRequest$outboundSchema` instead. */
  export const outboundSchema = MessagesGetRequest$outboundSchema;
  /** @deprecated use `MessagesGetRequest$Outbound` instead. */
  export type Outbound = MessagesGetRequest$Outbound;
}
