/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ThreadsDeleteRequest = {
  /**
   * The ID of the thread to delete
   */
  threadId: string;
};

/** @internal */
export const ThreadsDeleteRequest$inboundSchema: z.ZodType<
  ThreadsDeleteRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  thread_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "thread_id": "threadId",
  });
});

/** @internal */
export type ThreadsDeleteRequest$Outbound = {
  thread_id: string;
};

/** @internal */
export const ThreadsDeleteRequest$outboundSchema: z.ZodType<
  ThreadsDeleteRequest$Outbound,
  z.ZodTypeDef,
  ThreadsDeleteRequest
> = z.object({
  threadId: z.string(),
}).transform((v) => {
  return remap$(v, {
    threadId: "thread_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ThreadsDeleteRequest$ {
  /** @deprecated use `ThreadsDeleteRequest$inboundSchema` instead. */
  export const inboundSchema = ThreadsDeleteRequest$inboundSchema;
  /** @deprecated use `ThreadsDeleteRequest$outboundSchema` instead. */
  export const outboundSchema = ThreadsDeleteRequest$outboundSchema;
  /** @deprecated use `ThreadsDeleteRequest$Outbound` instead. */
  export type Outbound = ThreadsDeleteRequest$Outbound;
}

export function threadsDeleteRequestToJSON(
  threadsDeleteRequest: ThreadsDeleteRequest,
): string {
  return JSON.stringify(
    ThreadsDeleteRequest$outboundSchema.parse(threadsDeleteRequest),
  );
}

export function threadsDeleteRequestFromJSON(
  jsonString: string,
): SafeParseResult<ThreadsDeleteRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreadsDeleteRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreadsDeleteRequest' from JSON`,
  );
}
