/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ThreadsRunRequest = {
  /**
   * The ID of the thread to run
   */
  threadId: string;
  threadRun: components.ThreadRun;
};

/** @internal */
export const ThreadsRunRequest$inboundSchema: z.ZodType<
  ThreadsRunRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  thread_id: z.string(),
  ThreadRun: components.ThreadRun$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "thread_id": "threadId",
    "ThreadRun": "threadRun",
  });
});

/** @internal */
export type ThreadsRunRequest$Outbound = {
  thread_id: string;
  ThreadRun: components.ThreadRun$Outbound;
};

/** @internal */
export const ThreadsRunRequest$outboundSchema: z.ZodType<
  ThreadsRunRequest$Outbound,
  z.ZodTypeDef,
  ThreadsRunRequest
> = z.object({
  threadId: z.string(),
  threadRun: components.ThreadRun$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    threadId: "thread_id",
    threadRun: "ThreadRun",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ThreadsRunRequest$ {
  /** @deprecated use `ThreadsRunRequest$inboundSchema` instead. */
  export const inboundSchema = ThreadsRunRequest$inboundSchema;
  /** @deprecated use `ThreadsRunRequest$outboundSchema` instead. */
  export const outboundSchema = ThreadsRunRequest$outboundSchema;
  /** @deprecated use `ThreadsRunRequest$Outbound` instead. */
  export type Outbound = ThreadsRunRequest$Outbound;
}

export function threadsRunRequestToJSON(
  threadsRunRequest: ThreadsRunRequest,
): string {
  return JSON.stringify(
    ThreadsRunRequest$outboundSchema.parse(threadsRunRequest),
  );
}

export function threadsRunRequestFromJSON(
  jsonString: string,
): SafeParseResult<ThreadsRunRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreadsRunRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreadsRunRequest' from JSON`,
  );
}
