/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ThreadsGetRequest = {
  /**
   * The ID of the thread to retrieve
   */
  threadId: string;
};

/** @internal */
export const ThreadsGetRequest$inboundSchema: z.ZodType<
  ThreadsGetRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  thread_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "thread_id": "threadId",
  });
});

/** @internal */
export type ThreadsGetRequest$Outbound = {
  thread_id: string;
};

/** @internal */
export const ThreadsGetRequest$outboundSchema: z.ZodType<
  ThreadsGetRequest$Outbound,
  z.ZodTypeDef,
  ThreadsGetRequest
> = z.object({
  threadId: z.string(),
}).transform((v) => {
  return remap$(v, {
    threadId: "thread_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ThreadsGetRequest$ {
  /** @deprecated use `ThreadsGetRequest$inboundSchema` instead. */
  export const inboundSchema = ThreadsGetRequest$inboundSchema;
  /** @deprecated use `ThreadsGetRequest$outboundSchema` instead. */
  export const outboundSchema = ThreadsGetRequest$outboundSchema;
  /** @deprecated use `ThreadsGetRequest$Outbound` instead. */
  export type Outbound = ThreadsGetRequest$Outbound;
}

export function threadsGetRequestToJSON(
  threadsGetRequest: ThreadsGetRequest,
): string {
  return JSON.stringify(
    ThreadsGetRequest$outboundSchema.parse(threadsGetRequest),
  );
}

export function threadsGetRequestFromJSON(
  jsonString: string,
): SafeParseResult<ThreadsGetRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreadsGetRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreadsGetRequest' from JSON`,
  );
}
