/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest = {
    teamId: string;
    memberId: string;
};

/** @internal */
export const CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest$inboundSchema: z.ZodType<
    CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        team_id: z.string(),
        member_id: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            team_id: "teamId",
            member_id: "memberId",
        });
    });

/** @internal */
export type CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest$Outbound = {
    team_id: string;
    member_id: string;
};

/** @internal */
export const CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest$outboundSchema: z.ZodType<
    CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest$Outbound,
    z.ZodTypeDef,
    CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest
> = z
    .object({
        teamId: z.string(),
        memberId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            teamId: "team_id",
            memberId: "member_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest$ {
    /** @deprecated use `CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest$inboundSchema` instead. */
    export const inboundSchema = CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest$inboundSchema;
    /** @deprecated use `CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest$outboundSchema` instead. */
    export const outboundSchema =
        CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest$outboundSchema;
    /** @deprecated use `CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest$Outbound` instead. */
    export type Outbound = CreateTeamMemberTeamMemberTeamIdMemberIdPostRequest$Outbound;
}
