/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DeleteSkillSkillsDeleteDeleteRequest = {
    skillId: number;
};

/** @internal */
export const DeleteSkillSkillsDeleteDeleteRequest$inboundSchema: z.ZodType<
    DeleteSkillSkillsDeleteDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        skill_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            skill_id: "skillId",
        });
    });

/** @internal */
export type DeleteSkillSkillsDeleteDeleteRequest$Outbound = {
    skill_id: number;
};

/** @internal */
export const DeleteSkillSkillsDeleteDeleteRequest$outboundSchema: z.ZodType<
    DeleteSkillSkillsDeleteDeleteRequest$Outbound,
    z.ZodTypeDef,
    DeleteSkillSkillsDeleteDeleteRequest
> = z
    .object({
        skillId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            skillId: "skill_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteSkillSkillsDeleteDeleteRequest$ {
    /** @deprecated use `DeleteSkillSkillsDeleteDeleteRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteSkillSkillsDeleteDeleteRequest$inboundSchema;
    /** @deprecated use `DeleteSkillSkillsDeleteDeleteRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteSkillSkillsDeleteDeleteRequest$outboundSchema;
    /** @deprecated use `DeleteSkillSkillsDeleteDeleteRequest$Outbound` instead. */
    export type Outbound = DeleteSkillSkillsDeleteDeleteRequest$Outbound;
}
