/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DeleteTeamTeamDeleteRequest = {
    teamId: string;
};

/** @internal */
export const DeleteTeamTeamDeleteRequest$inboundSchema: z.ZodType<
    DeleteTeamTeamDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        team_id: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            team_id: "teamId",
        });
    });

/** @internal */
export type DeleteTeamTeamDeleteRequest$Outbound = {
    team_id: string;
};

/** @internal */
export const DeleteTeamTeamDeleteRequest$outboundSchema: z.ZodType<
    DeleteTeamTeamDeleteRequest$Outbound,
    z.ZodTypeDef,
    DeleteTeamTeamDeleteRequest
> = z
    .object({
        teamId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            teamId: "team_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteTeamTeamDeleteRequest$ {
    /** @deprecated use `DeleteTeamTeamDeleteRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteTeamTeamDeleteRequest$inboundSchema;
    /** @deprecated use `DeleteTeamTeamDeleteRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteTeamTeamDeleteRequest$outboundSchema;
    /** @deprecated use `DeleteTeamTeamDeleteRequest$Outbound` instead. */
    export type Outbound = DeleteTeamTeamDeleteRequest$Outbound;
}
