/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest = {
    knowledgeBaseId: number;
};

/** @internal */
export const DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest$inboundSchema: z.ZodType<
    DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        knowledge_base_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            knowledge_base_id: "knowledgeBaseId",
        });
    });

/** @internal */
export type DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest$Outbound = {
    knowledge_base_id: number;
};

/** @internal */
export const DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest$outboundSchema: z.ZodType<
    DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest$Outbound,
    z.ZodTypeDef,
    DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest
> = z
    .object({
        knowledgeBaseId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            knowledgeBaseId: "knowledge_base_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest$ {
    /** @deprecated use `DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest$inboundSchema;
    /** @deprecated use `DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest$outboundSchema` instead. */
    export const outboundSchema =
        DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest$outboundSchema;
    /** @deprecated use `DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest$Outbound` instead. */
    export type Outbound = DeleteKnowledgeBaseKnowledgeBasesDeleteDeleteRequest$Outbound;
}
