/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DeleteAgentAgentsDeleteDeleteRequest = {
    agentId: number;
};

/** @internal */
export const DeleteAgentAgentsDeleteDeleteRequest$inboundSchema: z.ZodType<
    DeleteAgentAgentsDeleteDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        agent_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agent_id: "agentId",
        });
    });

/** @internal */
export type DeleteAgentAgentsDeleteDeleteRequest$Outbound = {
    agent_id: number;
};

/** @internal */
export const DeleteAgentAgentsDeleteDeleteRequest$outboundSchema: z.ZodType<
    DeleteAgentAgentsDeleteDeleteRequest$Outbound,
    z.ZodTypeDef,
    DeleteAgentAgentsDeleteDeleteRequest
> = z
    .object({
        agentId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agentId: "agent_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAgentAgentsDeleteDeleteRequest$ {
    /** @deprecated use `DeleteAgentAgentsDeleteDeleteRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteAgentAgentsDeleteDeleteRequest$inboundSchema;
    /** @deprecated use `DeleteAgentAgentsDeleteDeleteRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteAgentAgentsDeleteDeleteRequest$outboundSchema;
    /** @deprecated use `DeleteAgentAgentsDeleteDeleteRequest$Outbound` instead. */
    export type Outbound = DeleteAgentAgentsDeleteDeleteRequest$Outbound;
}
