/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DeleteSessionSessionsDeleteDeleteRequest = {
    sessionId: number;
};

/** @internal */
export const DeleteSessionSessionsDeleteDeleteRequest$inboundSchema: z.ZodType<
    DeleteSessionSessionsDeleteDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        session_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            session_id: "sessionId",
        });
    });

/** @internal */
export type DeleteSessionSessionsDeleteDeleteRequest$Outbound = {
    session_id: number;
};

/** @internal */
export const DeleteSessionSessionsDeleteDeleteRequest$outboundSchema: z.ZodType<
    DeleteSessionSessionsDeleteDeleteRequest$Outbound,
    z.ZodTypeDef,
    DeleteSessionSessionsDeleteDeleteRequest
> = z
    .object({
        sessionId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            sessionId: "session_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteSessionSessionsDeleteDeleteRequest$ {
    /** @deprecated use `DeleteSessionSessionsDeleteDeleteRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteSessionSessionsDeleteDeleteRequest$inboundSchema;
    /** @deprecated use `DeleteSessionSessionsDeleteDeleteRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteSessionSessionsDeleteDeleteRequest$outboundSchema;
    /** @deprecated use `DeleteSessionSessionsDeleteDeleteRequest$Outbound` instead. */
    export type Outbound = DeleteSessionSessionsDeleteDeleteRequest$Outbound;
}
