/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DeleteConnectorConnectorsDeleteDeleteRequest = {
    connectorId: number;
};

/** @internal */
export const DeleteConnectorConnectorsDeleteDeleteRequest$inboundSchema: z.ZodType<
    DeleteConnectorConnectorsDeleteDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        connector_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            connector_id: "connectorId",
        });
    });

/** @internal */
export type DeleteConnectorConnectorsDeleteDeleteRequest$Outbound = {
    connector_id: number;
};

/** @internal */
export const DeleteConnectorConnectorsDeleteDeleteRequest$outboundSchema: z.ZodType<
    DeleteConnectorConnectorsDeleteDeleteRequest$Outbound,
    z.ZodTypeDef,
    DeleteConnectorConnectorsDeleteDeleteRequest
> = z
    .object({
        connectorId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            connectorId: "connector_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteConnectorConnectorsDeleteDeleteRequest$ {
    /** @deprecated use `DeleteConnectorConnectorsDeleteDeleteRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteConnectorConnectorsDeleteDeleteRequest$inboundSchema;
    /** @deprecated use `DeleteConnectorConnectorsDeleteDeleteRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteConnectorConnectorsDeleteDeleteRequest$outboundSchema;
    /** @deprecated use `DeleteConnectorConnectorsDeleteDeleteRequest$Outbound` instead. */
    export type Outbound = DeleteConnectorConnectorsDeleteDeleteRequest$Outbound;
}
