/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest = {
    teamId: string;
    memberId: string;
};

/** @internal */
export const DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest$inboundSchema: z.ZodType<
    DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        team_id: z.string(),
        member_id: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            team_id: "teamId",
            member_id: "memberId",
        });
    });

/** @internal */
export type DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest$Outbound = {
    team_id: string;
    member_id: string;
};

/** @internal */
export const DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest$outboundSchema: z.ZodType<
    DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest$Outbound,
    z.ZodTypeDef,
    DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest
> = z
    .object({
        teamId: z.string(),
        memberId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            teamId: "team_id",
            memberId: "member_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest$ {
    /** @deprecated use `DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest$inboundSchema` instead. */
    export const inboundSchema =
        DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest$inboundSchema;
    /** @deprecated use `DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest$outboundSchema` instead. */
    export const outboundSchema =
        DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest$outboundSchema;
    /** @deprecated use `DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest$Outbound` instead. */
    export type Outbound = DeleteTeamMemberTeamMemberTeamIdMemberIdDeleteRequest$Outbound;
}
