/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DeleteWorkflowWorkflowsDeleteDeleteRequest = {
    workflowId: number;
};

/** @internal */
export const DeleteWorkflowWorkflowsDeleteDeleteRequest$inboundSchema: z.ZodType<
    DeleteWorkflowWorkflowsDeleteDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        workflow_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            workflow_id: "workflowId",
        });
    });

/** @internal */
export type DeleteWorkflowWorkflowsDeleteDeleteRequest$Outbound = {
    workflow_id: number;
};

/** @internal */
export const DeleteWorkflowWorkflowsDeleteDeleteRequest$outboundSchema: z.ZodType<
    DeleteWorkflowWorkflowsDeleteDeleteRequest$Outbound,
    z.ZodTypeDef,
    DeleteWorkflowWorkflowsDeleteDeleteRequest
> = z
    .object({
        workflowId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            workflowId: "workflow_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteWorkflowWorkflowsDeleteDeleteRequest$ {
    /** @deprecated use `DeleteWorkflowWorkflowsDeleteDeleteRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteWorkflowWorkflowsDeleteDeleteRequest$inboundSchema;
    /** @deprecated use `DeleteWorkflowWorkflowsDeleteDeleteRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteWorkflowWorkflowsDeleteDeleteRequest$outboundSchema;
    /** @deprecated use `DeleteWorkflowWorkflowsDeleteDeleteRequest$Outbound` instead. */
    export type Outbound = DeleteWorkflowWorkflowsDeleteDeleteRequest$Outbound;
}
