/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DeleteModelModelsDeleteDeleteRequest = {
    modelId: number;
};

/** @internal */
export const DeleteModelModelsDeleteDeleteRequest$inboundSchema: z.ZodType<
    DeleteModelModelsDeleteDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        model_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            model_id: "modelId",
        });
    });

/** @internal */
export type DeleteModelModelsDeleteDeleteRequest$Outbound = {
    model_id: number;
};

/** @internal */
export const DeleteModelModelsDeleteDeleteRequest$outboundSchema: z.ZodType<
    DeleteModelModelsDeleteDeleteRequest$Outbound,
    z.ZodTypeDef,
    DeleteModelModelsDeleteDeleteRequest
> = z
    .object({
        modelId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            modelId: "model_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteModelModelsDeleteDeleteRequest$ {
    /** @deprecated use `DeleteModelModelsDeleteDeleteRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteModelModelsDeleteDeleteRequest$inboundSchema;
    /** @deprecated use `DeleteModelModelsDeleteDeleteRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteModelModelsDeleteDeleteRequest$outboundSchema;
    /** @deprecated use `DeleteModelModelsDeleteDeleteRequest$Outbound` instead. */
    export type Outbound = DeleteModelModelsDeleteDeleteRequest$Outbound;
}
