/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type FilesRetrieveFilesSessionIdFilePathGetRequest = {
    sessionId: number;
    filePath: string;
};

/** @internal */
export const FilesRetrieveFilesSessionIdFilePathGetRequest$inboundSchema: z.ZodType<
    FilesRetrieveFilesSessionIdFilePathGetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        session_id: z.number().int(),
        file_path: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            session_id: "sessionId",
            file_path: "filePath",
        });
    });

/** @internal */
export type FilesRetrieveFilesSessionIdFilePathGetRequest$Outbound = {
    session_id: number;
    file_path: string;
};

/** @internal */
export const FilesRetrieveFilesSessionIdFilePathGetRequest$outboundSchema: z.ZodType<
    FilesRetrieveFilesSessionIdFilePathGetRequest$Outbound,
    z.ZodTypeDef,
    FilesRetrieveFilesSessionIdFilePathGetRequest
> = z
    .object({
        sessionId: z.number().int(),
        filePath: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            sessionId: "session_id",
            filePath: "file_path",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FilesRetrieveFilesSessionIdFilePathGetRequest$ {
    /** @deprecated use `FilesRetrieveFilesSessionIdFilePathGetRequest$inboundSchema` instead. */
    export const inboundSchema = FilesRetrieveFilesSessionIdFilePathGetRequest$inboundSchema;
    /** @deprecated use `FilesRetrieveFilesSessionIdFilePathGetRequest$outboundSchema` instead. */
    export const outboundSchema = FilesRetrieveFilesSessionIdFilePathGetRequest$outboundSchema;
    /** @deprecated use `FilesRetrieveFilesSessionIdFilePathGetRequest$Outbound` instead. */
    export type Outbound = FilesRetrieveFilesSessionIdFilePathGetRequest$Outbound;
}
