/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type FilesListFilesSessionIdGetRequest = {
    sessionId: number;
};

/** @internal */
export const FilesListFilesSessionIdGetRequest$inboundSchema: z.ZodType<
    FilesListFilesSessionIdGetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        session_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            session_id: "sessionId",
        });
    });

/** @internal */
export type FilesListFilesSessionIdGetRequest$Outbound = {
    session_id: number;
};

/** @internal */
export const FilesListFilesSessionIdGetRequest$outboundSchema: z.ZodType<
    FilesListFilesSessionIdGetRequest$Outbound,
    z.ZodTypeDef,
    FilesListFilesSessionIdGetRequest
> = z
    .object({
        sessionId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            sessionId: "session_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FilesListFilesSessionIdGetRequest$ {
    /** @deprecated use `FilesListFilesSessionIdGetRequest$inboundSchema` instead. */
    export const inboundSchema = FilesListFilesSessionIdGetRequest$inboundSchema;
    /** @deprecated use `FilesListFilesSessionIdGetRequest$outboundSchema` instead. */
    export const outboundSchema = FilesListFilesSessionIdGetRequest$outboundSchema;
    /** @deprecated use `FilesListFilesSessionIdGetRequest$Outbound` instead. */
    export type Outbound = FilesListFilesSessionIdGetRequest$Outbound;
}
