/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type FilesUploadFilesSessionIdPostRequest = {
    sessionId: number;
    bodyFilesUploadFilesSessionIdPost: components.BodyFilesUploadFilesSessionIdPost;
};

/** @internal */
export const FilesUploadFilesSessionIdPostRequest$inboundSchema: z.ZodType<
    FilesUploadFilesSessionIdPostRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        session_id: z.number().int(),
        Body_files_upload_files__session_id__post:
            components.BodyFilesUploadFilesSessionIdPost$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            session_id: "sessionId",
            Body_files_upload_files__session_id__post: "bodyFilesUploadFilesSessionIdPost",
        });
    });

/** @internal */
export type FilesUploadFilesSessionIdPostRequest$Outbound = {
    session_id: number;
    Body_files_upload_files__session_id__post: components.BodyFilesUploadFilesSessionIdPost$Outbound;
};

/** @internal */
export const FilesUploadFilesSessionIdPostRequest$outboundSchema: z.ZodType<
    FilesUploadFilesSessionIdPostRequest$Outbound,
    z.ZodTypeDef,
    FilesUploadFilesSessionIdPostRequest
> = z
    .object({
        sessionId: z.number().int(),
        bodyFilesUploadFilesSessionIdPost:
            components.BodyFilesUploadFilesSessionIdPost$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            sessionId: "session_id",
            bodyFilesUploadFilesSessionIdPost: "Body_files_upload_files__session_id__post",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FilesUploadFilesSessionIdPostRequest$ {
    /** @deprecated use `FilesUploadFilesSessionIdPostRequest$inboundSchema` instead. */
    export const inboundSchema = FilesUploadFilesSessionIdPostRequest$inboundSchema;
    /** @deprecated use `FilesUploadFilesSessionIdPostRequest$outboundSchema` instead. */
    export const outboundSchema = FilesUploadFilesSessionIdPostRequest$outboundSchema;
    /** @deprecated use `FilesUploadFilesSessionIdPostRequest$Outbound` instead. */
    export type Outbound = FilesUploadFilesSessionIdPostRequest$Outbound;
}
