/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetAgentKbsAgentsLinkKbAgentIdGetRequest = {
    agentId: number;
};

/** @internal */
export const GetAgentKbsAgentsLinkKbAgentIdGetRequest$inboundSchema: z.ZodType<
    GetAgentKbsAgentsLinkKbAgentIdGetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        agent_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agent_id: "agentId",
        });
    });

/** @internal */
export type GetAgentKbsAgentsLinkKbAgentIdGetRequest$Outbound = {
    agent_id: number;
};

/** @internal */
export const GetAgentKbsAgentsLinkKbAgentIdGetRequest$outboundSchema: z.ZodType<
    GetAgentKbsAgentsLinkKbAgentIdGetRequest$Outbound,
    z.ZodTypeDef,
    GetAgentKbsAgentsLinkKbAgentIdGetRequest
> = z
    .object({
        agentId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agentId: "agent_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAgentKbsAgentsLinkKbAgentIdGetRequest$ {
    /** @deprecated use `GetAgentKbsAgentsLinkKbAgentIdGetRequest$inboundSchema` instead. */
    export const inboundSchema = GetAgentKbsAgentsLinkKbAgentIdGetRequest$inboundSchema;
    /** @deprecated use `GetAgentKbsAgentsLinkKbAgentIdGetRequest$outboundSchema` instead. */
    export const outboundSchema = GetAgentKbsAgentsLinkKbAgentIdGetRequest$outboundSchema;
    /** @deprecated use `GetAgentKbsAgentsLinkKbAgentIdGetRequest$Outbound` instead. */
    export type Outbound = GetAgentKbsAgentsLinkKbAgentIdGetRequest$Outbound;
}
