/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetAgentSkillsAgentsLinkSkillAgentIdGetRequest = {
    agentId: number;
};

/** @internal */
export const GetAgentSkillsAgentsLinkSkillAgentIdGetRequest$inboundSchema: z.ZodType<
    GetAgentSkillsAgentsLinkSkillAgentIdGetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        agent_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agent_id: "agentId",
        });
    });

/** @internal */
export type GetAgentSkillsAgentsLinkSkillAgentIdGetRequest$Outbound = {
    agent_id: number;
};

/** @internal */
export const GetAgentSkillsAgentsLinkSkillAgentIdGetRequest$outboundSchema: z.ZodType<
    GetAgentSkillsAgentsLinkSkillAgentIdGetRequest$Outbound,
    z.ZodTypeDef,
    GetAgentSkillsAgentsLinkSkillAgentIdGetRequest
> = z
    .object({
        agentId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agentId: "agent_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAgentSkillsAgentsLinkSkillAgentIdGetRequest$ {
    /** @deprecated use `GetAgentSkillsAgentsLinkSkillAgentIdGetRequest$inboundSchema` instead. */
    export const inboundSchema = GetAgentSkillsAgentsLinkSkillAgentIdGetRequest$inboundSchema;
    /** @deprecated use `GetAgentSkillsAgentsLinkSkillAgentIdGetRequest$outboundSchema` instead. */
    export const outboundSchema = GetAgentSkillsAgentsLinkSkillAgentIdGetRequest$outboundSchema;
    /** @deprecated use `GetAgentSkillsAgentsLinkSkillAgentIdGetRequest$Outbound` instead. */
    export type Outbound = GetAgentSkillsAgentsLinkSkillAgentIdGetRequest$Outbound;
}
