/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetAgentModelsAgentsLinkModelAgentIdGetRequest = {
    agentId: number;
};

/** @internal */
export const GetAgentModelsAgentsLinkModelAgentIdGetRequest$inboundSchema: z.ZodType<
    GetAgentModelsAgentsLinkModelAgentIdGetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        agent_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agent_id: "agentId",
        });
    });

/** @internal */
export type GetAgentModelsAgentsLinkModelAgentIdGetRequest$Outbound = {
    agent_id: number;
};

/** @internal */
export const GetAgentModelsAgentsLinkModelAgentIdGetRequest$outboundSchema: z.ZodType<
    GetAgentModelsAgentsLinkModelAgentIdGetRequest$Outbound,
    z.ZodTypeDef,
    GetAgentModelsAgentsLinkModelAgentIdGetRequest
> = z
    .object({
        agentId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agentId: "agent_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAgentModelsAgentsLinkModelAgentIdGetRequest$ {
    /** @deprecated use `GetAgentModelsAgentsLinkModelAgentIdGetRequest$inboundSchema` instead. */
    export const inboundSchema = GetAgentModelsAgentsLinkModelAgentIdGetRequest$inboundSchema;
    /** @deprecated use `GetAgentModelsAgentsLinkModelAgentIdGetRequest$outboundSchema` instead. */
    export const outboundSchema = GetAgentModelsAgentsLinkModelAgentIdGetRequest$outboundSchema;
    /** @deprecated use `GetAgentModelsAgentsLinkModelAgentIdGetRequest$Outbound` instead. */
    export type Outbound = GetAgentModelsAgentsLinkModelAgentIdGetRequest$Outbound;
}
