/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest = {
    knowledgeBaseId: number;
};

/** @internal */
export const GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest$inboundSchema: z.ZodType<
    GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        knowledge_base_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            knowledge_base_id: "knowledgeBaseId",
        });
    });

/** @internal */
export type GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest$Outbound =
    {
        knowledge_base_id: number;
    };

/** @internal */
export const GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest$outboundSchema: z.ZodType<
    GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest$Outbound,
    z.ZodTypeDef,
    GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest
> = z
    .object({
        knowledgeBaseId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            knowledgeBaseId: "knowledge_base_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest$ {
    /** @deprecated use `GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest$inboundSchema` instead. */
    export const inboundSchema =
        GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest$inboundSchema;
    /** @deprecated use `GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest$outboundSchema` instead. */
    export const outboundSchema =
        GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest$outboundSchema;
    /** @deprecated use `GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest$Outbound` instead. */
    export type Outbound =
        GetKnowledgeBaseConnectorsKnowledgeBasesLinkConnectorKnowledgeBaseIdGetRequest$Outbound;
}
