/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest = {
    workflowId: number;
    agentType: string;
};

/** @internal */
export const GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest$inboundSchema: z.ZodType<
    GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        workflow_id: z.number().int(),
        agent_type: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            workflow_id: "workflowId",
            agent_type: "agentType",
        });
    });

/** @internal */
export type GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest$Outbound = {
    workflow_id: number;
    agent_type: string;
};

/** @internal */
export const GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest$outboundSchema: z.ZodType<
    GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest$Outbound,
    z.ZodTypeDef,
    GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest
> = z
    .object({
        workflowId: z.number().int(),
        agentType: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            workflowId: "workflow_id",
            agentType: "agent_type",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest$ {
    /** @deprecated use `GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest$inboundSchema` instead. */
    export const inboundSchema =
        GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest$inboundSchema;
    /** @deprecated use `GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest$outboundSchema` instead. */
    export const outboundSchema =
        GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest$outboundSchema;
    /** @deprecated use `GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest$Outbound` instead. */
    export type Outbound =
        GetLinkedWorkflowAgentsWorkflowsLinkAgentWorkflowIdAgentTypeGetRequest$Outbound;
}
