/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest = {
    agentId: number;
};

/** @internal */
export const GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest$inboundSchema: z.ZodType<
    GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        agent_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agent_id: "agentId",
        });
    });

/** @internal */
export type GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest$Outbound = {
    agent_id: number;
};

/** @internal */
export const GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest$outboundSchema: z.ZodType<
    GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest$Outbound,
    z.ZodTypeDef,
    GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest
> = z
    .object({
        agentId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agentId: "agent_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest$ {
    /** @deprecated use `GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest$inboundSchema` instead. */
    export const inboundSchema = GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest$inboundSchema;
    /** @deprecated use `GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest$outboundSchema` instead. */
    export const outboundSchema = GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest$outboundSchema;
    /** @deprecated use `GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest$Outbound` instead. */
    export type Outbound = GetLinkedAgentsAgentsLinkAgentAgentIdGetRequest$Outbound;
}
