/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type GetWorkflowWorkflowsWorkflowIdGetRequest = {
    workflowId: number;
};

/** @internal */
export const GetWorkflowWorkflowsWorkflowIdGetRequest$inboundSchema: z.ZodType<
    GetWorkflowWorkflowsWorkflowIdGetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        workflow_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            workflow_id: "workflowId",
        });
    });

/** @internal */
export type GetWorkflowWorkflowsWorkflowIdGetRequest$Outbound = {
    workflow_id: number;
};

/** @internal */
export const GetWorkflowWorkflowsWorkflowIdGetRequest$outboundSchema: z.ZodType<
    GetWorkflowWorkflowsWorkflowIdGetRequest$Outbound,
    z.ZodTypeDef,
    GetWorkflowWorkflowsWorkflowIdGetRequest
> = z
    .object({
        workflowId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            workflowId: "workflow_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWorkflowWorkflowsWorkflowIdGetRequest$ {
    /** @deprecated use `GetWorkflowWorkflowsWorkflowIdGetRequest$inboundSchema` instead. */
    export const inboundSchema = GetWorkflowWorkflowsWorkflowIdGetRequest$inboundSchema;
    /** @deprecated use `GetWorkflowWorkflowsWorkflowIdGetRequest$outboundSchema` instead. */
    export const outboundSchema = GetWorkflowWorkflowsWorkflowIdGetRequest$outboundSchema;
    /** @deprecated use `GetWorkflowWorkflowsWorkflowIdGetRequest$Outbound` instead. */
    export type Outbound = GetWorkflowWorkflowsWorkflowIdGetRequest$Outbound;
}
