/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest = {
    agentId: number;
    modelId: number;
};

/** @internal */
export const LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest$inboundSchema: z.ZodType<
    LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        agent_id: z.number().int(),
        model_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agent_id: "agentId",
            model_id: "modelId",
        });
    });

/** @internal */
export type LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest$Outbound = {
    agent_id: number;
    model_id: number;
};

/** @internal */
export const LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest$outboundSchema: z.ZodType<
    LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest$Outbound,
    z.ZodTypeDef,
    LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest
> = z
    .object({
        agentId: z.number().int(),
        modelId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agentId: "agent_id",
            modelId: "model_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest$ {
    /** @deprecated use `LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest$inboundSchema` instead. */
    export const inboundSchema =
        LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest$inboundSchema;
    /** @deprecated use `LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest$outboundSchema` instead. */
    export const outboundSchema =
        LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest$outboundSchema;
    /** @deprecated use `LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest$Outbound` instead. */
    export type Outbound = LinkAgentModelAgentsLinkModelAgentIdModelIdPostRequest$Outbound;
}
