/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest =
    {
        knowledgeBaseId: number;
        connectorId: number;
    };

/** @internal */
export const LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest$inboundSchema: z.ZodType<
    LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        knowledge_base_id: z.number().int(),
        connector_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            knowledge_base_id: "knowledgeBaseId",
            connector_id: "connectorId",
        });
    });

/** @internal */
export type LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest$Outbound =
    {
        knowledge_base_id: number;
        connector_id: number;
    };

/** @internal */
export const LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest$outboundSchema: z.ZodType<
    LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest$Outbound,
    z.ZodTypeDef,
    LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest
> = z
    .object({
        knowledgeBaseId: z.number().int(),
        connectorId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            knowledgeBaseId: "knowledge_base_id",
            connectorId: "connector_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest$ {
    /** @deprecated use `LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest$inboundSchema` instead. */
    export const inboundSchema =
        LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest$inboundSchema;
    /** @deprecated use `LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest$outboundSchema` instead. */
    export const outboundSchema =
        LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest$outboundSchema;
    /** @deprecated use `LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest$Outbound` instead. */
    export type Outbound =
        LinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdPostRequest$Outbound;
}
