/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest = {
    primaryAgentId: number;
    secondaryAgentId: number;
};

/** @internal */
export const LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest$inboundSchema: z.ZodType<
    LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        primary_agent_id: z.number().int(),
        secondary_agent_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            primary_agent_id: "primaryAgentId",
            secondary_agent_id: "secondaryAgentId",
        });
    });

/** @internal */
export type LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest$Outbound = {
    primary_agent_id: number;
    secondary_agent_id: number;
};

/** @internal */
export const LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest$outboundSchema: z.ZodType<
    LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest$Outbound,
    z.ZodTypeDef,
    LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest
> = z
    .object({
        primaryAgentId: z.number().int(),
        secondaryAgentId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            primaryAgentId: "primary_agent_id",
            secondaryAgentId: "secondary_agent_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest$ {
    /** @deprecated use `LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest$inboundSchema` instead. */
    export const inboundSchema =
        LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest$inboundSchema;
    /** @deprecated use `LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest$outboundSchema` instead. */
    export const outboundSchema =
        LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest$outboundSchema;
    /** @deprecated use `LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest$Outbound` instead. */
    export type Outbound =
        LinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdPostRequest$Outbound;
}
