/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest = {
    workflowId: number;
    agentId: number;
    agentType: string;
};

/** @internal */
export const LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest$inboundSchema: z.ZodType<
    LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        workflow_id: z.number().int(),
        agent_id: z.number().int(),
        agent_type: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            workflow_id: "workflowId",
            agent_id: "agentId",
            agent_type: "agentType",
        });
    });

/** @internal */
export type LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest$Outbound = {
    workflow_id: number;
    agent_id: number;
    agent_type: string;
};

/** @internal */
export const LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest$outboundSchema: z.ZodType<
    LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest$Outbound,
    z.ZodTypeDef,
    LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest
> = z
    .object({
        workflowId: z.number().int(),
        agentId: z.number().int(),
        agentType: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            workflowId: "workflow_id",
            agentId: "agent_id",
            agentType: "agent_type",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest$ {
    /** @deprecated use `LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest$inboundSchema` instead. */
    export const inboundSchema =
        LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest$inboundSchema;
    /** @deprecated use `LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest$outboundSchema` instead. */
    export const outboundSchema =
        LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest$outboundSchema;
    /** @deprecated use `LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest$Outbound` instead. */
    export type Outbound =
        LinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypePostRequest$Outbound;
}
