/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest = {
    agentId: number;
    kbId: number;
};

/** @internal */
export const LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest$inboundSchema: z.ZodType<
    LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        agent_id: z.number().int(),
        kb_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agent_id: "agentId",
            kb_id: "kbId",
        });
    });

/** @internal */
export type LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest$Outbound = {
    agent_id: number;
    kb_id: number;
};

/** @internal */
export const LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest$outboundSchema: z.ZodType<
    LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest$Outbound,
    z.ZodTypeDef,
    LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest
> = z
    .object({
        agentId: z.number().int(),
        kbId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agentId: "agent_id",
            kbId: "kb_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest$ {
    /** @deprecated use `LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest$inboundSchema` instead. */
    export const inboundSchema = LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest$inboundSchema;
    /** @deprecated use `LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest$outboundSchema` instead. */
    export const outboundSchema = LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest$outboundSchema;
    /** @deprecated use `LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest$Outbound` instead. */
    export type Outbound = LinkAgentKbAgentsLinkKbAgentIdKbIdPostRequest$Outbound;
}
