/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest = {
    agentId: number;
    skillId: number;
};

/** @internal */
export const LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest$inboundSchema: z.ZodType<
    LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        agent_id: z.number().int(),
        skill_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agent_id: "agentId",
            skill_id: "skillId",
        });
    });

/** @internal */
export type LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest$Outbound = {
    agent_id: number;
    skill_id: number;
};

/** @internal */
export const LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest$outboundSchema: z.ZodType<
    LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest$Outbound,
    z.ZodTypeDef,
    LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest
> = z
    .object({
        agentId: z.number().int(),
        skillId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agentId: "agent_id",
            skillId: "skill_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest$ {
    /** @deprecated use `LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest$inboundSchema` instead. */
    export const inboundSchema =
        LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest$inboundSchema;
    /** @deprecated use `LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest$outboundSchema` instead. */
    export const outboundSchema =
        LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest$outboundSchema;
    /** @deprecated use `LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest$Outbound` instead. */
    export type Outbound = LinkAgentSkillAgentsLinkSkillAgentIdSkillIdPostRequest$Outbound;
}
