/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type ListTeamMembersTeamMemberTeamIdGetRequest = {
    teamId: string;
};

/** @internal */
export const ListTeamMembersTeamMemberTeamIdGetRequest$inboundSchema: z.ZodType<
    ListTeamMembersTeamMemberTeamIdGetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        team_id: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            team_id: "teamId",
        });
    });

/** @internal */
export type ListTeamMembersTeamMemberTeamIdGetRequest$Outbound = {
    team_id: string;
};

/** @internal */
export const ListTeamMembersTeamMemberTeamIdGetRequest$outboundSchema: z.ZodType<
    ListTeamMembersTeamMemberTeamIdGetRequest$Outbound,
    z.ZodTypeDef,
    ListTeamMembersTeamMemberTeamIdGetRequest
> = z
    .object({
        teamId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            teamId: "team_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListTeamMembersTeamMemberTeamIdGetRequest$ {
    /** @deprecated use `ListTeamMembersTeamMemberTeamIdGetRequest$inboundSchema` instead. */
    export const inboundSchema = ListTeamMembersTeamMemberTeamIdGetRequest$inboundSchema;
    /** @deprecated use `ListTeamMembersTeamMemberTeamIdGetRequest$outboundSchema` instead. */
    export const outboundSchema = ListTeamMembersTeamMemberTeamIdGetRequest$outboundSchema;
    /** @deprecated use `ListTeamMembersTeamMemberTeamIdGetRequest$Outbound` instead. */
    export type Outbound = ListTeamMembersTeamMemberTeamIdGetRequest$Outbound;
}
