/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type ListMessagesSessionsSessionIdMessagesGetRequest = {
    sessionId: number;
};

/** @internal */
export const ListMessagesSessionsSessionIdMessagesGetRequest$inboundSchema: z.ZodType<
    ListMessagesSessionsSessionIdMessagesGetRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        session_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            session_id: "sessionId",
        });
    });

/** @internal */
export type ListMessagesSessionsSessionIdMessagesGetRequest$Outbound = {
    session_id: number;
};

/** @internal */
export const ListMessagesSessionsSessionIdMessagesGetRequest$outboundSchema: z.ZodType<
    ListMessagesSessionsSessionIdMessagesGetRequest$Outbound,
    z.ZodTypeDef,
    ListMessagesSessionsSessionIdMessagesGetRequest
> = z
    .object({
        sessionId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            sessionId: "session_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListMessagesSessionsSessionIdMessagesGetRequest$ {
    /** @deprecated use `ListMessagesSessionsSessionIdMessagesGetRequest$inboundSchema` instead. */
    export const inboundSchema = ListMessagesSessionsSessionIdMessagesGetRequest$inboundSchema;
    /** @deprecated use `ListMessagesSessionsSessionIdMessagesGetRequest$outboundSchema` instead. */
    export const outboundSchema = ListMessagesSessionsSessionIdMessagesGetRequest$outboundSchema;
    /** @deprecated use `ListMessagesSessionsSessionIdMessagesGetRequest$Outbound` instead. */
    export type Outbound = ListMessagesSessionsSessionIdMessagesGetRequest$Outbound;
}
