/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest = {
    sessionId: number;
    workflowId: number;
    runWorkflowRequest: components.RunWorkflowRequest;
};

/** @internal */
export const RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest$inboundSchema: z.ZodType<
    RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        session_id: z.number().int(),
        workflow_id: z.number().int(),
        RunWorkflowRequest: components.RunWorkflowRequest$inboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            session_id: "sessionId",
            workflow_id: "workflowId",
            RunWorkflowRequest: "runWorkflowRequest",
        });
    });

/** @internal */
export type RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest$Outbound = {
    session_id: number;
    workflow_id: number;
    RunWorkflowRequest: components.RunWorkflowRequest$Outbound;
};

/** @internal */
export const RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest$outboundSchema: z.ZodType<
    RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest$Outbound,
    z.ZodTypeDef,
    RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest
> = z
    .object({
        sessionId: z.number().int(),
        workflowId: z.number().int(),
        runWorkflowRequest: components.RunWorkflowRequest$outboundSchema,
    })
    .transform((v) => {
        return remap$(v, {
            sessionId: "session_id",
            workflowId: "workflow_id",
            runWorkflowRequest: "RunWorkflowRequest",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest$ {
    /** @deprecated use `RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest$inboundSchema` instead. */
    export const inboundSchema =
        RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest$inboundSchema;
    /** @deprecated use `RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest$outboundSchema` instead. */
    export const outboundSchema =
        RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest$outboundSchema;
    /** @deprecated use `RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest$Outbound` instead. */
    export type Outbound =
        RunSessionWorkflowSessionsSessionIdWorkflowWorkflowIdRunPostRequest$Outbound;
}
