/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest =
    {
        knowledgeBaseId: number;
        connectorId: number;
    };

/** @internal */
export const UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest$inboundSchema: z.ZodType<
    UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        knowledge_base_id: z.number().int(),
        connector_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            knowledge_base_id: "knowledgeBaseId",
            connector_id: "connectorId",
        });
    });

/** @internal */
export type UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest$Outbound =
    {
        knowledge_base_id: number;
        connector_id: number;
    };

/** @internal */
export const UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest$outboundSchema: z.ZodType<
    UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest$Outbound,
    z.ZodTypeDef,
    UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest
> = z
    .object({
        knowledgeBaseId: z.number().int(),
        connectorId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            knowledgeBaseId: "knowledge_base_id",
            connectorId: "connector_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest$ {
    /** @deprecated use `UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest$inboundSchema` instead. */
    export const inboundSchema =
        UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest$inboundSchema;
    /** @deprecated use `UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest$outboundSchema` instead. */
    export const outboundSchema =
        UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest$outboundSchema;
    /** @deprecated use `UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest$Outbound` instead. */
    export type Outbound =
        UnlinkKnowledgeBaseConnectorKnowledgeBasesLinkConnectorKnowledgeBaseIdConnectorIdDeleteRequest$Outbound;
}
