/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest = {
    agentId: number;
    kbId: number;
};

/** @internal */
export const UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest$inboundSchema: z.ZodType<
    UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        agent_id: z.number().int(),
        kb_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agent_id: "agentId",
            kb_id: "kbId",
        });
    });

/** @internal */
export type UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest$Outbound = {
    agent_id: number;
    kb_id: number;
};

/** @internal */
export const UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest$outboundSchema: z.ZodType<
    UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest$Outbound,
    z.ZodTypeDef,
    UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest
> = z
    .object({
        agentId: z.number().int(),
        kbId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agentId: "agent_id",
            kbId: "kb_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest$ {
    /** @deprecated use `UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest$inboundSchema` instead. */
    export const inboundSchema = UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest$inboundSchema;
    /** @deprecated use `UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest$outboundSchema` instead. */
    export const outboundSchema = UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest$outboundSchema;
    /** @deprecated use `UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest$Outbound` instead. */
    export type Outbound = UnlinkAgentKbAgentsLinkKbAgentIdKbIdDeleteRequest$Outbound;
}
