/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest = {
    agentId: number;
    modelId: number;
};

/** @internal */
export const UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest$inboundSchema: z.ZodType<
    UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        agent_id: z.number().int(),
        model_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agent_id: "agentId",
            model_id: "modelId",
        });
    });

/** @internal */
export type UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest$Outbound = {
    agent_id: number;
    model_id: number;
};

/** @internal */
export const UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest$outboundSchema: z.ZodType<
    UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest$Outbound,
    z.ZodTypeDef,
    UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest
> = z
    .object({
        agentId: z.number().int(),
        modelId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agentId: "agent_id",
            modelId: "model_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest$ {
    /** @deprecated use `UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest$inboundSchema` instead. */
    export const inboundSchema =
        UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest$inboundSchema;
    /** @deprecated use `UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest$outboundSchema` instead. */
    export const outboundSchema =
        UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest$outboundSchema;
    /** @deprecated use `UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest$Outbound` instead. */
    export type Outbound = UnlinkAgentModelAgentsLinkModelAgentIdModelIdDeleteRequest$Outbound;
}
