/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest = {
    workflowId: number;
    agentId: number;
    agentType: string;
};

/** @internal */
export const UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest$inboundSchema: z.ZodType<
    UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        workflow_id: z.number().int(),
        agent_id: z.number().int(),
        agent_type: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            workflow_id: "workflowId",
            agent_id: "agentId",
            agent_type: "agentType",
        });
    });

/** @internal */
export type UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest$Outbound =
    {
        workflow_id: number;
        agent_id: number;
        agent_type: string;
    };

/** @internal */
export const UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest$outboundSchema: z.ZodType<
    UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest$Outbound,
    z.ZodTypeDef,
    UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest
> = z
    .object({
        workflowId: z.number().int(),
        agentId: z.number().int(),
        agentType: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            workflowId: "workflow_id",
            agentId: "agent_id",
            agentType: "agent_type",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest$ {
    /** @deprecated use `UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest$inboundSchema` instead. */
    export const inboundSchema =
        UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest$inboundSchema;
    /** @deprecated use `UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest$outboundSchema` instead. */
    export const outboundSchema =
        UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest$outboundSchema;
    /** @deprecated use `UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest$Outbound` instead. */
    export type Outbound =
        UnlinkWorkflowAgentWorkflowsLinkAgentWorkflowIdAgentIdAgentTypeDeleteRequest$Outbound;
}
