/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest = {
    agentId: number;
    skillId: number;
};

/** @internal */
export const UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest$inboundSchema: z.ZodType<
    UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        agent_id: z.number().int(),
        skill_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agent_id: "agentId",
            skill_id: "skillId",
        });
    });

/** @internal */
export type UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest$Outbound = {
    agent_id: number;
    skill_id: number;
};

/** @internal */
export const UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest$outboundSchema: z.ZodType<
    UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest$Outbound,
    z.ZodTypeDef,
    UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest
> = z
    .object({
        agentId: z.number().int(),
        skillId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            agentId: "agent_id",
            skillId: "skill_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest$ {
    /** @deprecated use `UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest$inboundSchema` instead. */
    export const inboundSchema =
        UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest$inboundSchema;
    /** @deprecated use `UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest$outboundSchema` instead. */
    export const outboundSchema =
        UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest$outboundSchema;
    /** @deprecated use `UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest$Outbound` instead. */
    export type Outbound = UnlinkAgentSkillAgentsLinkSkillAgentIdSkillIdDeleteRequest$Outbound;
}
