/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest = {
    primaryAgentId: number;
    secondaryAgentId: number;
};

/** @internal */
export const UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest$inboundSchema: z.ZodType<
    UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        primary_agent_id: z.number().int(),
        secondary_agent_id: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            primary_agent_id: "primaryAgentId",
            secondary_agent_id: "secondaryAgentId",
        });
    });

/** @internal */
export type UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest$Outbound = {
    primary_agent_id: number;
    secondary_agent_id: number;
};

/** @internal */
export const UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest$outboundSchema: z.ZodType<
    UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest$Outbound,
    z.ZodTypeDef,
    UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest
> = z
    .object({
        primaryAgentId: z.number().int(),
        secondaryAgentId: z.number().int(),
    })
    .transform((v) => {
        return remap$(v, {
            primaryAgentId: "primary_agent_id",
            secondaryAgentId: "secondary_agent_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest$ {
    /** @deprecated use `UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest$inboundSchema` instead. */
    export const inboundSchema =
        UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest$inboundSchema;
    /** @deprecated use `UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest$outboundSchema` instead. */
    export const outboundSchema =
        UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest$outboundSchema;
    /** @deprecated use `UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest$Outbound` instead. */
    export type Outbound =
        UnlinkAgentAgentAgentsLinkAgentPrimaryAgentIdSecondaryAgentIdDeleteRequest$Outbound;
}
