/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { runsRunsCreate } from "../funcs/runsRunsCreate.js";
import { runsRunsList } from "../funcs/runsRunsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Runs extends ClientSDK {
    async runsList(options?: RequestOptions): Promise<Array<components.Run>> {
        return unwrapAsync(runsRunsList(this, options));
    }

    async runsCreate(
        request: components.RunCreate,
        options?: RequestOptions
    ): Promise<components.Run> {
        return unwrapAsync(runsRunsCreate(this, request, options));
    }
}
