/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Files } from "./files.js";
import { Runs } from "./runs.js";

export class Polydoc extends ClientSDK {
    private _files?: Files;
    get files(): Files {
        return (this._files ??= new Files(this.options$));
    }

    private _runs?: Runs;
    get runs(): Runs {
        return (this._runs ??= new Runs(this.options$));
    }
}
