workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Polydoc-OAS:
        inputs:
            - location: ../../../../backend/server/docs/openapi.yml
        registry:
            location: registry.speakeasyapi.dev/edgenai/edgenai/polydoc-oas
targets:
    polydoc:
        target: typescript
        source: Polydoc-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/edgenai/edgenai/polydoc-oas-code-samples
            blocking: false
