/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  MessageRole,
  MessageRole$inboundSchema,
  MessageRole$outboundSchema,
} from "./messagerole.js";

export type Message = {
  accountId: string;
  content: string;
  createdAt: Date;
  id: string;
  role: MessageRole;
  threadId: string;
};

/** @internal */
export const Message$inboundSchema: z.ZodType<Message, z.ZodTypeDef, unknown> =
  z.object({
    account_id: z.string(),
    content: z.string(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ),
    id: z.string(),
    role: MessageRole$inboundSchema,
    thread_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "account_id": "accountId",
      "created_at": "createdAt",
      "thread_id": "threadId",
    });
  });

/** @internal */
export type Message$Outbound = {
  account_id: string;
  content: string;
  created_at: string;
  id: string;
  role: string;
  thread_id: string;
};

/** @internal */
export const Message$outboundSchema: z.ZodType<
  Message$Outbound,
  z.ZodTypeDef,
  Message
> = z.object({
  accountId: z.string(),
  content: z.string(),
  createdAt: z.date().transform(v => v.toISOString()),
  id: z.string(),
  role: MessageRole$outboundSchema,
  threadId: z.string(),
}).transform((v) => {
  return remap$(v, {
    accountId: "account_id",
    createdAt: "created_at",
    threadId: "thread_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Message$ {
  /** @deprecated use `Message$inboundSchema` instead. */
  export const inboundSchema = Message$inboundSchema;
  /** @deprecated use `Message$outboundSchema` instead. */
  export const outboundSchema = Message$outboundSchema;
  /** @deprecated use `Message$Outbound` instead. */
  export type Outbound = Message$Outbound;
}
